// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lumera/nft/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryToolpackRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryToolpackRequest) Reset()         { *m = QueryToolpackRequest{} }
func (m *QueryToolpackRequest) String() string { return proto.CompactTextString(m) }
func (*QueryToolpackRequest) ProtoMessage()    {}
func (*QueryToolpackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77b8a85bccb0b344, []int{0}
}
func (m *QueryToolpackRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryToolpackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryToolpackRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryToolpackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryToolpackRequest.Merge(m, src)
}
func (m *QueryToolpackRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryToolpackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryToolpackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryToolpackRequest proto.InternalMessageInfo

func (m *QueryToolpackRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryToolpackResponse struct {
	Toolpack *ToolpackNFT `protobuf:"bytes,1,opt,name=toolpack,proto3" json:"toolpack,omitempty"`
}

func (m *QueryToolpackResponse) Reset()         { *m = QueryToolpackResponse{} }
func (m *QueryToolpackResponse) String() string { return proto.CompactTextString(m) }
func (*QueryToolpackResponse) ProtoMessage()    {}
func (*QueryToolpackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77b8a85bccb0b344, []int{1}
}
func (m *QueryToolpackResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryToolpackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryToolpackResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryToolpackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryToolpackResponse.Merge(m, src)
}
func (m *QueryToolpackResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryToolpackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryToolpackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryToolpackResponse proto.InternalMessageInfo

func (m *QueryToolpackResponse) GetToolpack() *ToolpackNFT {
	if m != nil {
		return m.Toolpack
	}
	return nil
}

type QueryToolpacksByCuratorRequest struct {
	Curator string `protobuf:"bytes,1,opt,name=curator,proto3" json:"curator,omitempty"`
}

func (m *QueryToolpacksByCuratorRequest) Reset()         { *m = QueryToolpacksByCuratorRequest{} }
func (m *QueryToolpacksByCuratorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryToolpacksByCuratorRequest) ProtoMessage()    {}
func (*QueryToolpacksByCuratorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77b8a85bccb0b344, []int{2}
}
func (m *QueryToolpacksByCuratorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryToolpacksByCuratorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryToolpacksByCuratorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryToolpacksByCuratorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryToolpacksByCuratorRequest.Merge(m, src)
}
func (m *QueryToolpacksByCuratorRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryToolpacksByCuratorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryToolpacksByCuratorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryToolpacksByCuratorRequest proto.InternalMessageInfo

func (m *QueryToolpacksByCuratorRequest) GetCurator() string {
	if m != nil {
		return m.Curator
	}
	return ""
}

type QueryToolpacksByCuratorResponse struct {
	Toolpacks []*ToolpackNFT `protobuf:"bytes,1,rep,name=toolpacks,proto3" json:"toolpacks,omitempty"`
}

func (m *QueryToolpacksByCuratorResponse) Reset()         { *m = QueryToolpacksByCuratorResponse{} }
func (m *QueryToolpacksByCuratorResponse) String() string { return proto.CompactTextString(m) }
func (*QueryToolpacksByCuratorResponse) ProtoMessage()    {}
func (*QueryToolpacksByCuratorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77b8a85bccb0b344, []int{3}
}
func (m *QueryToolpacksByCuratorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryToolpacksByCuratorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryToolpacksByCuratorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryToolpacksByCuratorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryToolpacksByCuratorResponse.Merge(m, src)
}
func (m *QueryToolpacksByCuratorResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryToolpacksByCuratorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryToolpacksByCuratorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryToolpacksByCuratorResponse proto.InternalMessageInfo

func (m *QueryToolpacksByCuratorResponse) GetToolpacks() []*ToolpackNFT {
	if m != nil {
		return m.Toolpacks
	}
	return nil
}

type QueryToolpackHistoryRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryToolpackHistoryRequest) Reset()         { *m = QueryToolpackHistoryRequest{} }
func (m *QueryToolpackHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryToolpackHistoryRequest) ProtoMessage()    {}
func (*QueryToolpackHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77b8a85bccb0b344, []int{4}
}
func (m *QueryToolpackHistoryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryToolpackHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryToolpackHistoryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryToolpackHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryToolpackHistoryRequest.Merge(m, src)
}
func (m *QueryToolpackHistoryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryToolpackHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryToolpackHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryToolpackHistoryRequest proto.InternalMessageInfo

func (m *QueryToolpackHistoryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryToolpackHistoryResponse struct {
	History []*ToolpackHistory `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
}

func (m *QueryToolpackHistoryResponse) Reset()         { *m = QueryToolpackHistoryResponse{} }
func (m *QueryToolpackHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryToolpackHistoryResponse) ProtoMessage()    {}
func (*QueryToolpackHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77b8a85bccb0b344, []int{5}
}
func (m *QueryToolpackHistoryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryToolpackHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryToolpackHistoryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryToolpackHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryToolpackHistoryResponse.Merge(m, src)
}
func (m *QueryToolpackHistoryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryToolpackHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryToolpackHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryToolpackHistoryResponse proto.InternalMessageInfo

func (m *QueryToolpackHistoryResponse) GetHistory() []*ToolpackHistory {
	if m != nil {
		return m.History
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryToolpackRequest)(nil), "lumera.nft.v1.QueryToolpackRequest")
	proto.RegisterType((*QueryToolpackResponse)(nil), "lumera.nft.v1.QueryToolpackResponse")
	proto.RegisterType((*QueryToolpacksByCuratorRequest)(nil), "lumera.nft.v1.QueryToolpacksByCuratorRequest")
	proto.RegisterType((*QueryToolpacksByCuratorResponse)(nil), "lumera.nft.v1.QueryToolpacksByCuratorResponse")
	proto.RegisterType((*QueryToolpackHistoryRequest)(nil), "lumera.nft.v1.QueryToolpackHistoryRequest")
	proto.RegisterType((*QueryToolpackHistoryResponse)(nil), "lumera.nft.v1.QueryToolpackHistoryResponse")
}

func init() { proto.RegisterFile("lumera/nft/v1/query.proto", fileDescriptor_77b8a85bccb0b344) }

var fileDescriptor_77b8a85bccb0b344 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcc, 0x29, 0xcd, 0x4d,
	0x2d, 0x4a, 0xd4, 0xcf, 0x4b, 0x2b, 0xd1, 0x2f, 0x33, 0xd4, 0x2f, 0x2c, 0x4d, 0x2d, 0xaa, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x85, 0x48, 0xe9, 0xe5, 0xa5, 0x95, 0xe8, 0x95, 0x19,
	0x4a, 0xc9, 0xa0, 0xaa, 0x2c, 0xc9, 0xcf, 0xcf, 0x29, 0x48, 0x4c, 0xce, 0x86, 0x28, 0x56, 0x52,
	0xe3, 0x12, 0x09, 0x04, 0xe9, 0x0d, 0x81, 0x0a, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08,
	0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0xa6, 0x28,
	0xf9, 0x73, 0x89, 0xa2, 0xa9, 0x2b, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x32, 0xe3, 0xe2, 0x80,
	0x19, 0x09, 0x56, 0xce, 0x6d, 0x24, 0xa5, 0x87, 0xe2, 0x00, 0x3d, 0x98, 0x16, 0x3f, 0xb7, 0x90,
	0x20, 0xb8, 0x5a, 0x25, 0x2b, 0x2e, 0x39, 0x14, 0x03, 0x8b, 0x9d, 0x2a, 0x9d, 0x4b, 0x8b, 0x12,
	0x4b, 0xf2, 0x8b, 0x60, 0x4e, 0x90, 0xe0, 0x62, 0x4f, 0x86, 0x88, 0x40, 0xdd, 0x01, 0xe3, 0x2a,
	0x45, 0x73, 0xc9, 0xe3, 0xd4, 0x0b, 0x75, 0x96, 0x05, 0x17, 0x27, 0xcc, 0xaa, 0x62, 0x09, 0x46,
	0x05, 0x66, 0x02, 0xee, 0x42, 0x28, 0x56, 0xd2, 0xe5, 0x92, 0x46, 0x31, 0xdc, 0x23, 0xb3, 0xb8,
	0x24, 0xbf, 0xa8, 0x12, 0x57, 0xc0, 0x44, 0x70, 0xc9, 0x60, 0x57, 0x0e, 0x77, 0x08, 0x7b, 0x06,
	0x44, 0x08, 0xea, 0x0c, 0x39, 0x1c, 0xce, 0x80, 0x69, 0x84, 0x29, 0x37, 0xda, 0xcf, 0xc4, 0xc5,
	0x0a, 0x36, 0x5a, 0x28, 0x94, 0x8b, 0x03, 0xa6, 0x4a, 0x48, 0x19, 0x4d, 0x3b, 0xb6, 0xd8, 0x93,
	0x52, 0xc1, 0xaf, 0x08, 0xea, 0xb4, 0x62, 0x2e, 0x21, 0xcc, 0x10, 0x14, 0xd2, 0xc5, 0xa7, 0x17,
	0x23, 0x96, 0xa4, 0xf4, 0x88, 0x55, 0x0e, 0xb5, 0x34, 0x8b, 0x8b, 0x1f, 0xcd, 0xc7, 0x42, 0x5a,
	0xf8, 0x8c, 0x40, 0x0d, 0x7e, 0x29, 0x6d, 0xa2, 0xd4, 0x42, 0xec, 0x72, 0x52, 0x3d, 0xf1, 0x48,
	0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0,
	0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0xee, 0x0a, 0x70, 0x7e, 0x28, 0xa9, 0x2c, 0x48,
	0x2d, 0x4e, 0x62, 0x03, 0x67, 0x05, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x8e, 0x91,
	0x93, 0x54, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Toolpack(ctx context.Context, in *QueryToolpackRequest, opts ...grpc.CallOption) (*QueryToolpackResponse, error)
	ToolpacksByCurator(ctx context.Context, in *QueryToolpacksByCuratorRequest, opts ...grpc.CallOption) (*QueryToolpacksByCuratorResponse, error)
	ToolpackHistory(ctx context.Context, in *QueryToolpackHistoryRequest, opts ...grpc.CallOption) (*QueryToolpackHistoryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Toolpack(ctx context.Context, in *QueryToolpackRequest, opts ...grpc.CallOption) (*QueryToolpackResponse, error) {
	out := new(QueryToolpackResponse)
	err := c.cc.Invoke(ctx, "/lumera.nft.v1.Query/Toolpack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ToolpacksByCurator(ctx context.Context, in *QueryToolpacksByCuratorRequest, opts ...grpc.CallOption) (*QueryToolpacksByCuratorResponse, error) {
	out := new(QueryToolpacksByCuratorResponse)
	err := c.cc.Invoke(ctx, "/lumera.nft.v1.Query/ToolpacksByCurator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ToolpackHistory(ctx context.Context, in *QueryToolpackHistoryRequest, opts ...grpc.CallOption) (*QueryToolpackHistoryResponse, error) {
	out := new(QueryToolpackHistoryResponse)
	err := c.cc.Invoke(ctx, "/lumera.nft.v1.Query/ToolpackHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Toolpack(context.Context, *QueryToolpackRequest) (*QueryToolpackResponse, error)
	ToolpacksByCurator(context.Context, *QueryToolpacksByCuratorRequest) (*QueryToolpacksByCuratorResponse, error)
	ToolpackHistory(context.Context, *QueryToolpackHistoryRequest) (*QueryToolpackHistoryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Toolpack(ctx context.Context, req *QueryToolpackRequest) (*QueryToolpackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Toolpack not implemented")
}
func (*UnimplementedQueryServer) ToolpacksByCurator(ctx context.Context, req *QueryToolpacksByCuratorRequest) (*QueryToolpacksByCuratorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToolpacksByCurator not implemented")
}
func (*UnimplementedQueryServer) ToolpackHistory(ctx context.Context, req *QueryToolpackHistoryRequest) (*QueryToolpackHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToolpackHistory not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Toolpack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryToolpackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Toolpack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumera.nft.v1.Query/Toolpack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Toolpack(ctx, req.(*QueryToolpackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ToolpacksByCurator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryToolpacksByCuratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ToolpacksByCurator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumera.nft.v1.Query/ToolpacksByCurator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ToolpacksByCurator(ctx, req.(*QueryToolpacksByCuratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ToolpackHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryToolpackHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ToolpackHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumera.nft.v1.Query/ToolpackHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ToolpackHistory(ctx, req.(*QueryToolpackHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lumera.nft.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Toolpack",
			Handler:    _Query_Toolpack_Handler,
		},
		{
			MethodName: "ToolpacksByCurator",
			Handler:    _Query_ToolpacksByCurator_Handler,
		},
		{
			MethodName: "ToolpackHistory",
			Handler:    _Query_ToolpackHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lumera/nft/v1/query.proto",
}

func (m *QueryToolpackRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryToolpackRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryToolpackRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryToolpackResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryToolpackResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryToolpackResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Toolpack != nil {
		{
			size, err := m.Toolpack.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryToolpacksByCuratorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryToolpacksByCuratorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryToolpacksByCuratorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Curator) > 0 {
		i -= len(m.Curator)
		copy(dAtA[i:], m.Curator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Curator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryToolpacksByCuratorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryToolpacksByCuratorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryToolpacksByCuratorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Toolpacks) > 0 {
		for iNdEx := len(m.Toolpacks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Toolpacks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryToolpackHistoryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryToolpackHistoryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryToolpackHistoryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryToolpackHistoryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryToolpackHistoryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryToolpackHistoryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.History) > 0 {
		for iNdEx := len(m.History) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.History[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryToolpackRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryToolpackResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Toolpack != nil {
		l = m.Toolpack.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryToolpacksByCuratorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Curator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryToolpacksByCuratorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Toolpacks) > 0 {
		for _, e := range m.Toolpacks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryToolpackHistoryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryToolpackHistoryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.History) > 0 {
		for _, e := range m.History {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryToolpackRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryToolpackRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryToolpackRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryToolpackResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryToolpackResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryToolpackResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Toolpack", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Toolpack == nil {
				m.Toolpack = &ToolpackNFT{}
			}
			if err := m.Toolpack.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryToolpacksByCuratorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryToolpacksByCuratorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryToolpacksByCuratorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Curator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Curator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryToolpacksByCuratorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryToolpacksByCuratorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryToolpacksByCuratorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Toolpacks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Toolpacks = append(m.Toolpacks, &ToolpackNFT{})
			if err := m.Toolpacks[len(m.Toolpacks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryToolpackHistoryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryToolpackHistoryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryToolpackHistoryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryToolpackHistoryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryToolpackHistoryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryToolpackHistoryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field History", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.History = append(m.History, &ToolpackHistory{})
			if err := m.History[len(m.History)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
