// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lumera/vaults/v1/vault.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Vault represents a prepaid capacity commitment purchased by a policy owner.
type Vault struct {
	Id              string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner           string     `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	PolicyId        string     `protobuf:"bytes,3,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	ToolId          string     `protobuf:"bytes,4,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	Tier            string     `protobuf:"bytes,5,opt,name=tier,proto3" json:"tier,omitempty"`
	PrepaidAmount   types.Coin `protobuf:"bytes,6,opt,name=prepaid_amount,json=prepaidAmount,proto3" json:"prepaid_amount"`
	RemainingAmount types.Coin `protobuf:"bytes,7,opt,name=remaining_amount,json=remainingAmount,proto3" json:"remaining_amount"`
	DiscountBps     uint32     `protobuf:"varint,8,opt,name=discount_bps,json=discountBps,proto3" json:"discount_bps,omitempty"`
	StartTime       time.Time  `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time"`
	ExpireTime      time.Time  `protobuf:"bytes,10,opt,name=expire_time,json=expireTime,proto3,stdtime" json:"expire_time"`
	RolloverAllowed bool       `protobuf:"varint,11,opt,name=rollover_allowed,json=rolloverAllowed,proto3" json:"rollover_allowed,omitempty"`
	CommitmentId    string     `protobuf:"bytes,12,opt,name=commitment_id,json=commitmentId,proto3" json:"commitment_id,omitempty"`
}

func (m *Vault) Reset()         { *m = Vault{} }
func (m *Vault) String() string { return proto.CompactTextString(m) }
func (*Vault) ProtoMessage()    {}
func (*Vault) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a50ed770e9852a7, []int{0}
}
func (m *Vault) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Vault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Vault.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Vault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vault.Merge(m, src)
}
func (m *Vault) XXX_Size() int {
	return m.Size()
}
func (m *Vault) XXX_DiscardUnknown() {
	xxx_messageInfo_Vault.DiscardUnknown(m)
}

var xxx_messageInfo_Vault proto.InternalMessageInfo

func (m *Vault) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vault) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Vault) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *Vault) GetToolId() string {
	if m != nil {
		return m.ToolId
	}
	return ""
}

func (m *Vault) GetTier() string {
	if m != nil {
		return m.Tier
	}
	return ""
}

func (m *Vault) GetPrepaidAmount() types.Coin {
	if m != nil {
		return m.PrepaidAmount
	}
	return types.Coin{}
}

func (m *Vault) GetRemainingAmount() types.Coin {
	if m != nil {
		return m.RemainingAmount
	}
	return types.Coin{}
}

func (m *Vault) GetDiscountBps() uint32 {
	if m != nil {
		return m.DiscountBps
	}
	return 0
}

func (m *Vault) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *Vault) GetExpireTime() time.Time {
	if m != nil {
		return m.ExpireTime
	}
	return time.Time{}
}

func (m *Vault) GetRolloverAllowed() bool {
	if m != nil {
		return m.RolloverAllowed
	}
	return false
}

func (m *Vault) GetCommitmentId() string {
	if m != nil {
		return m.CommitmentId
	}
	return ""
}

func init() {
	proto.RegisterType((*Vault)(nil), "lumera.vaults.v1.Vault")
}

func init() { proto.RegisterFile("lumera/vaults/v1/vault.proto", fileDescriptor_5a50ed770e9852a7) }

var fileDescriptor_5a50ed770e9852a7 = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xbd, 0x8e, 0xd3, 0x40,
	0x18, 0xcc, 0x86, 0x24, 0x97, 0x6c, 0x7e, 0x2e, 0xac, 0x4e, 0xc2, 0x04, 0xe4, 0x04, 0x68, 0x02,
	0xc5, 0x5a, 0x81, 0x27, 0xb8, 0x9c, 0x28, 0x22, 0x0a, 0xa4, 0x08, 0x51, 0xd0, 0x44, 0x6b, 0x7b,
	0xb1, 0x56, 0xf2, 0xfa, 0xb3, 0x76, 0x37, 0xbe, 0xbb, 0xb7, 0xb8, 0x82, 0x87, 0xa0, 0xe4, 0x31,
	0xae, 0xbc, 0x92, 0x0a, 0x50, 0x52, 0xf0, 0x1a, 0x68, 0x77, 0x6d, 0xae, 0xbe, 0x26, 0x9a, 0x6f,
	0x26, 0x33, 0x9f, 0x3f, 0x8f, 0xf1, 0xf3, 0x7c, 0x2f, 0xb9, 0x62, 0x51, 0xc5, 0xf6, 0xb9, 0xd1,
	0x51, 0xb5, 0xf2, 0x88, 0x96, 0x0a, 0x0c, 0x90, 0xa9, 0x57, 0xa9, 0x57, 0x69, 0xb5, 0x9a, 0x85,
	0x09, 0x68, 0x09, 0x3a, 0x8a, 0x99, 0xe6, 0x51, 0xb5, 0x8a, 0xb9, 0x61, 0xab, 0x28, 0x01, 0x51,
	0x78, 0xc7, 0x6c, 0x9e, 0x01, 0x64, 0x39, 0x8f, 0xdc, 0x14, 0xef, 0xbf, 0x46, 0x46, 0x48, 0xae,
	0x0d, 0x93, 0x65, 0xfd, 0x87, 0xb3, 0x0c, 0x32, 0x70, 0x30, 0xb2, 0xa8, 0x66, 0x1f, 0x33, 0x29,
	0x0a, 0x88, 0xdc, 0xaf, 0xa7, 0x5e, 0x7e, 0xeb, 0xe0, 0xee, 0x67, 0xbb, 0x97, 0x4c, 0x70, 0x5b,
	0xa4, 0x01, 0x5a, 0xa0, 0xe5, 0x60, 0xdb, 0x16, 0x29, 0x39, 0xc3, 0x5d, 0xb8, 0x2c, 0xb8, 0x0a,
	0xda, 0x8e, 0xf2, 0x03, 0x79, 0x86, 0x07, 0x25, 0xe4, 0x22, 0xb9, 0xde, 0x89, 0x34, 0x78, 0xe4,
	0x94, 0xbe, 0x27, 0x36, 0x29, 0x79, 0x82, 0x4f, 0x0c, 0x40, 0x6e, 0xa5, 0x8e, 0x93, 0x7a, 0x76,
	0xdc, 0xa4, 0x84, 0xe0, 0x8e, 0x11, 0x5c, 0x05, 0x5d, 0xc7, 0x3a, 0x4c, 0x3e, 0xe0, 0x49, 0xa9,
	0x78, 0xc9, 0x44, 0xba, 0x63, 0x12, 0xf6, 0x85, 0x09, 0x7a, 0x0b, 0xb4, 0x1c, 0xbe, 0x7d, 0x4a,
	0xfd, 0xf1, 0xd4, 0x1e, 0x4f, 0xeb, 0xe3, 0xe9, 0x05, 0x88, 0x62, 0x3d, 0xb8, 0xfd, 0x35, 0x6f,
	0x7d, 0xff, 0xfb, 0xe3, 0x0d, 0xda, 0x8e, 0x6b, 0xef, 0xb9, 0xb3, 0x92, 0x8f, 0x78, 0xaa, 0xb8,
	0x64, 0xa2, 0x10, 0x45, 0xd6, 0xc4, 0x9d, 0x3c, 0x20, 0xee, 0xf4, 0xbf, 0xbb, 0x0e, 0x7c, 0x81,
	0x47, 0xa9, 0xd0, 0x89, 0xc5, 0xbb, 0xb8, 0xd4, 0x41, 0x7f, 0x81, 0x96, 0xe3, 0xed, 0xb0, 0xe1,
	0xd6, 0xa5, 0x26, 0x17, 0x18, 0x6b, 0xc3, 0x94, 0xd9, 0xd9, 0x97, 0x1f, 0x0c, 0xdc, 0xb6, 0x19,
	0xf5, 0xcd, 0xd0, 0xa6, 0x19, 0xfa, 0xa9, 0x69, 0x66, 0xdd, 0xb7, 0xeb, 0x6e, 0x7e, 0xcf, 0xd1,
	0x76, 0xe0, 0x7c, 0x56, 0x21, 0xef, 0xf1, 0x90, 0x5f, 0x95, 0x42, 0x71, 0x9f, 0x82, 0x1f, 0x90,
	0x82, 0xbd, 0xd1, 0xc5, 0xbc, 0xc6, 0x53, 0x05, 0x79, 0x0e, 0x15, 0x57, 0x3b, 0x96, 0xe7, 0x70,
	0xc9, 0xd3, 0x60, 0xb8, 0x40, 0xcb, 0xfe, 0xf6, 0xb4, 0xe1, 0xcf, 0x3d, 0x4d, 0x5e, 0xe1, 0x71,
	0x02, 0x52, 0x0a, 0x23, 0x79, 0x61, 0x6c, 0x55, 0x23, 0x57, 0xca, 0xe8, 0x9e, 0xdc, 0xa4, 0xeb,
	0xe5, 0xed, 0x21, 0x44, 0x77, 0x87, 0x10, 0xfd, 0x39, 0x84, 0xe8, 0xe6, 0x18, 0xb6, 0xee, 0x8e,
	0x61, 0xeb, 0xe7, 0x31, 0x6c, 0x7d, 0x99, 0x5c, 0x35, 0x5f, 0xb1, 0xb9, 0x2e, 0xb9, 0x8e, 0x7b,
	0xee, 0x19, 0xdf, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x1d, 0xd6, 0x68, 0xe3, 0x02, 0x00,
	0x00,
}

func (m *Vault) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Vault) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Vault) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CommitmentId) > 0 {
		i -= len(m.CommitmentId)
		copy(dAtA[i:], m.CommitmentId)
		i = encodeVarintVault(dAtA, i, uint64(len(m.CommitmentId)))
		i--
		dAtA[i] = 0x62
	}
	if m.RolloverAllowed {
		i--
		if m.RolloverAllowed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ExpireTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExpireTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintVault(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x52
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintVault(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x4a
	if m.DiscountBps != 0 {
		i = encodeVarintVault(dAtA, i, uint64(m.DiscountBps))
		i--
		dAtA[i] = 0x40
	}
	{
		size, err := m.RemainingAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintVault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.PrepaidAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintVault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.Tier) > 0 {
		i -= len(m.Tier)
		copy(dAtA[i:], m.Tier)
		i = encodeVarintVault(dAtA, i, uint64(len(m.Tier)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ToolId) > 0 {
		i -= len(m.ToolId)
		copy(dAtA[i:], m.ToolId)
		i = encodeVarintVault(dAtA, i, uint64(len(m.ToolId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PolicyId) > 0 {
		i -= len(m.PolicyId)
		copy(dAtA[i:], m.PolicyId)
		i = encodeVarintVault(dAtA, i, uint64(len(m.PolicyId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintVault(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintVault(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVault(dAtA []byte, offset int, v uint64) int {
	offset -= sovVault(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Vault) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.PolicyId)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.ToolId)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.Tier)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = m.PrepaidAmount.Size()
	n += 1 + l + sovVault(uint64(l))
	l = m.RemainingAmount.Size()
	n += 1 + l + sovVault(uint64(l))
	if m.DiscountBps != 0 {
		n += 1 + sovVault(uint64(m.DiscountBps))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovVault(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExpireTime)
	n += 1 + l + sovVault(uint64(l))
	if m.RolloverAllowed {
		n += 2
	}
	l = len(m.CommitmentId)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	return n
}

func sovVault(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVault(x uint64) (n int) {
	return sovVault(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Vault) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVault
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Vault: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Vault: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToolId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToolId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrepaidAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PrepaidAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RemainingAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiscountBps", wireType)
			}
			m.DiscountBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DiscountBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpireTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ExpireTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RolloverAllowed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RolloverAllowed = bool(v != 0)
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitmentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVault(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVault
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVault(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVault
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVault
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVault
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVault
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVault
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVault
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVault        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVault          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVault = fmt.Errorf("proto: unexpected end of group")
)
