
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lumera/cac/v1/query.proto

package types

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryGetCacheEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentHash   string                 `protobuf:"bytes,1,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetCacheEntryRequest) Reset() {
	*x = QueryGetCacheEntryRequest{}
	mi := &file_lumera_cac_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetCacheEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetCacheEntryRequest) ProtoMessage() {}

func (x *QueryGetCacheEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetCacheEntryRequest.ProtoReflect.Descriptor instead.
func (*QueryGetCacheEntryRequest) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryGetCacheEntryRequest) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

type QueryGetCacheEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *CacheEntry            `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetCacheEntryResponse) Reset() {
	*x = QueryGetCacheEntryResponse{}
	mi := &file_lumera_cac_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetCacheEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetCacheEntryResponse) ProtoMessage() {}

func (x *QueryGetCacheEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetCacheEntryResponse.ProtoReflect.Descriptor instead.
func (*QueryGetCacheEntryResponse) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryGetCacheEntryResponse) GetEntry() *CacheEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *QueryGetCacheEntryResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type QueryLookupByRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestHash   string                 `protobuf:"bytes,1,opt,name=request_hash,json=requestHash,proto3" json:"request_hash,omitempty"`
	ToolId        string                 `protobuf:"bytes,2,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"` // optional filter by tool
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLookupByRequestRequest) Reset() {
	*x = QueryLookupByRequestRequest{}
	mi := &file_lumera_cac_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLookupByRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLookupByRequestRequest) ProtoMessage() {}

func (x *QueryLookupByRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLookupByRequestRequest.ProtoReflect.Descriptor instead.
func (*QueryLookupByRequestRequest) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryLookupByRequestRequest) GetRequestHash() string {
	if x != nil {
		return x.RequestHash
	}
	return ""
}

func (x *QueryLookupByRequestRequest) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

type QueryLookupByRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CacheEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLookupByRequestResponse) Reset() {
	*x = QueryLookupByRequestResponse{}
	mi := &file_lumera_cac_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLookupByRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLookupByRequestResponse) ProtoMessage() {}

func (x *QueryLookupByRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLookupByRequestResponse.ProtoReflect.Descriptor instead.
func (*QueryLookupByRequestResponse) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryLookupByRequestResponse) GetEntries() []*CacheEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type QueryGetCacheStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetCacheStatsRequest) Reset() {
	*x = QueryGetCacheStatsRequest{}
	mi := &file_lumera_cac_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetCacheStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetCacheStatsRequest) ProtoMessage() {}

func (x *QueryGetCacheStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetCacheStatsRequest.ProtoReflect.Descriptor instead.
func (*QueryGetCacheStatsRequest) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_query_proto_rawDescGZIP(), []int{4}
}

type QueryGetCacheStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *CacheStats            `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetCacheStatsResponse) Reset() {
	*x = QueryGetCacheStatsResponse{}
	mi := &file_lumera_cac_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetCacheStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetCacheStatsResponse) ProtoMessage() {}

func (x *QueryGetCacheStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetCacheStatsResponse.ProtoReflect.Descriptor instead.
func (*QueryGetCacheStatsResponse) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryGetCacheStatsResponse) GetStats() *CacheStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type QueryListToolEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryListToolEntriesRequest) Reset() {
	*x = QueryListToolEntriesRequest{}
	mi := &file_lumera_cac_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryListToolEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryListToolEntriesRequest) ProtoMessage() {}

func (x *QueryListToolEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryListToolEntriesRequest.ProtoReflect.Descriptor instead.
func (*QueryListToolEntriesRequest) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryListToolEntriesRequest) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *QueryListToolEntriesRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryListToolEntriesRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type QueryListToolEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CacheEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryListToolEntriesResponse) Reset() {
	*x = QueryListToolEntriesResponse{}
	mi := &file_lumera_cac_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryListToolEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryListToolEntriesResponse) ProtoMessage() {}

func (x *QueryListToolEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryListToolEntriesResponse.ProtoReflect.Descriptor instead.
func (*QueryListToolEntriesResponse) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryListToolEntriesResponse) GetEntries() []*CacheEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *QueryListToolEntriesResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type QueryGetParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetParamsRequest) Reset() {
	*x = QueryGetParamsRequest{}
	mi := &file_lumera_cac_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetParamsRequest) ProtoMessage() {}

func (x *QueryGetParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryGetParamsRequest) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_query_proto_rawDescGZIP(), []int{8}
}

type QueryGetParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *CacheParams           `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetParamsResponse) Reset() {
	*x = QueryGetParamsResponse{}
	mi := &file_lumera_cac_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetParamsResponse) ProtoMessage() {}

func (x *QueryGetParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryGetParamsResponse) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryGetParamsResponse) GetParams() *CacheParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type ToolCacheStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	HitCount      uint64                 `protobuf:"varint,2,opt,name=hit_count,json=hitCount,proto3" json:"hit_count,omitempty"`
	MissCount     uint64                 `protobuf:"varint,3,opt,name=miss_count,json=missCount,proto3" json:"miss_count,omitempty"`
	HitRate       string                 `protobuf:"bytes,4,opt,name=hit_rate,json=hitRate,proto3" json:"hit_rate,omitempty"`
	OriginHits    map[string]uint64      `protobuf:"bytes,5,rep,name=origin_hits,json=originHits,proto3" json:"origin_hits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCacheStats) Reset() {
	*x = ToolCacheStats{}
	mi := &file_lumera_cac_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCacheStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCacheStats) ProtoMessage() {}

func (x *ToolCacheStats) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCacheStats.ProtoReflect.Descriptor instead.
func (*ToolCacheStats) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_query_proto_rawDescGZIP(), []int{10}
}

func (x *ToolCacheStats) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ToolCacheStats) GetHitCount() uint64 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

func (x *ToolCacheStats) GetMissCount() uint64 {
	if x != nil {
		return x.MissCount
	}
	return 0
}

func (x *ToolCacheStats) GetHitRate() string {
	if x != nil {
		return x.HitRate
	}
	return ""
}

func (x *ToolCacheStats) GetOriginHits() map[string]uint64 {
	if x != nil {
		return x.OriginHits
	}
	return nil
}

type QueryGetToolStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetToolStatsRequest) Reset() {
	*x = QueryGetToolStatsRequest{}
	mi := &file_lumera_cac_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetToolStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetToolStatsRequest) ProtoMessage() {}

func (x *QueryGetToolStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetToolStatsRequest.ProtoReflect.Descriptor instead.
func (*QueryGetToolStatsRequest) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *QueryGetToolStatsRequest) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

type QueryGetToolStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *ToolCacheStats        `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetToolStatsResponse) Reset() {
	*x = QueryGetToolStatsResponse{}
	mi := &file_lumera_cac_v1_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetToolStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetToolStatsResponse) ProtoMessage() {}

func (x *QueryGetToolStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetToolStatsResponse.ProtoReflect.Descriptor instead.
func (*QueryGetToolStatsResponse) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_query_proto_rawDescGZIP(), []int{12}
}

func (x *QueryGetToolStatsResponse) GetStats() *ToolCacheStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_lumera_cac_v1_query_proto protoreflect.FileDescriptor

const file_lumera_cac_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x19lumera/cac/v1/query.proto\x12\rlumera.cac.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19lumera/cac/v1/cache.proto\">\n" +
	"\x19QueryGetCacheEntryRequest\x12!\n" +
	"\fcontent_hash\x18\x01 \x01(\tR\vcontentHash\"c\n" +
	"\x1aQueryGetCacheEntryResponse\x12/\n" +
	"\x05entry\x18\x01 \x01(\v2\x19.lumera.cac.v1.CacheEntryR\x05entry\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"Y\n" +
	"\x1bQueryLookupByRequestRequest\x12!\n" +
	"\frequest_hash\x18\x01 \x01(\tR\vrequestHash\x12\x17\n" +
	"\atool_id\x18\x02 \x01(\tR\x06toolId\"S\n" +
	"\x1cQueryLookupByRequestResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.lumera.cac.v1.CacheEntryR\aentries\"\x1b\n" +
	"\x19QueryGetCacheStatsRequest\"M\n" +
	"\x1aQueryGetCacheStatsResponse\x12/\n" +
	"\x05stats\x18\x01 \x01(\v2\x19.lumera.cac.v1.CacheStatsR\x05stats\"d\n" +
	"\x1bQueryListToolEntriesRequest\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"t\n" +
	"\x1cQueryListToolEntriesResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.lumera.cac.v1.CacheEntryR\aentries\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\"\x17\n" +
	"\x15QueryGetParamsRequest\"L\n" +
	"\x16QueryGetParamsResponse\x122\n" +
	"\x06params\x18\x01 \x01(\v2\x1a.lumera.cac.v1.CacheParamsR\x06params\"\x8f\x02\n" +
	"\x0eToolCacheStats\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12\x1b\n" +
	"\thit_count\x18\x02 \x01(\x04R\bhitCount\x12\x1d\n" +
	"\n" +
	"miss_count\x18\x03 \x01(\x04R\tmissCount\x12\x19\n" +
	"\bhit_rate\x18\x04 \x01(\tR\ahitRate\x12N\n" +
	"\vorigin_hits\x18\x05 \x03(\v2-.lumera.cac.v1.ToolCacheStats.OriginHitsEntryR\n" +
	"originHits\x1a=\n" +
	"\x0fOriginHitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"3\n" +
	"\x18QueryGetToolStatsRequest\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\"P\n" +
	"\x19QueryGetToolStatsResponse\x123\n" +
	"\x05stats\x18\x01 \x01(\v2\x1d.lumera.cac.v1.ToolCacheStatsR\x05stats2\xe1\x06\n" +
	"\x05Query\x12\x91\x01\n" +
	"\rGetCacheEntry\x12(.lumera.cac.v1.QueryGetCacheEntryRequest\x1a).lumera.cac.v1.QueryGetCacheEntryResponse\"+\x82\xd3\xe4\x93\x02%\x12#/lumera/cac/v1/entry/{content_hash}\x12\x98\x01\n" +
	"\x0fLookupByRequest\x12*.lumera.cac.v1.QueryLookupByRequestRequest\x1a+.lumera.cac.v1.QueryLookupByRequestResponse\",\x82\xd3\xe4\x93\x02&\x12$/lumera/cac/v1/lookup/{request_hash}\x12\x82\x01\n" +
	"\rGetCacheStats\x12(.lumera.cac.v1.QueryGetCacheStatsRequest\x1a).lumera.cac.v1.QueryGetCacheStatsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/lumera/cac/v1/stats\x12\x99\x01\n" +
	"\x0fListToolEntries\x12*.lumera.cac.v1.QueryListToolEntriesRequest\x1a+.lumera.cac.v1.QueryListToolEntriesResponse\"-\x82\xd3\xe4\x93\x02'\x12%/lumera/cac/v1/tool/{tool_id}/entries\x12w\n" +
	"\tGetParams\x12$.lumera.cac.v1.QueryGetParamsRequest\x1a%.lumera.cac.v1.QueryGetParamsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/lumera/cac/v1/params\x12\x8e\x01\n" +
	"\fGetToolStats\x12'.lumera.cac.v1.QueryGetToolStatsRequest\x1a(.lumera.cac.v1.QueryGetToolStatsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/lumera/cac/v1/tool/{tool_id}/statsB1Z/github.com/LumeraProtocol/lumera/x/cac/typesb\x06proto3"

var (
	file_lumera_cac_v1_query_proto_rawDescOnce sync.Once
	file_lumera_cac_v1_query_proto_rawDescData []byte
)

func file_lumera_cac_v1_query_proto_rawDescGZIP() []byte {
	file_lumera_cac_v1_query_proto_rawDescOnce.Do(func() {
		file_lumera_cac_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lumera_cac_v1_query_proto_rawDesc), len(file_lumera_cac_v1_query_proto_rawDesc)))
	})
	return file_lumera_cac_v1_query_proto_rawDescData
}

var file_lumera_cac_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_lumera_cac_v1_query_proto_goTypes = []any{
	(*QueryGetCacheEntryRequest)(nil),    // 0: lumera.cac.v1.QueryGetCacheEntryRequest
	(*QueryGetCacheEntryResponse)(nil),   // 1: lumera.cac.v1.QueryGetCacheEntryResponse
	(*QueryLookupByRequestRequest)(nil),  // 2: lumera.cac.v1.QueryLookupByRequestRequest
	(*QueryLookupByRequestResponse)(nil), // 3: lumera.cac.v1.QueryLookupByRequestResponse
	(*QueryGetCacheStatsRequest)(nil),    // 4: lumera.cac.v1.QueryGetCacheStatsRequest
	(*QueryGetCacheStatsResponse)(nil),   // 5: lumera.cac.v1.QueryGetCacheStatsResponse
	(*QueryListToolEntriesRequest)(nil),  // 6: lumera.cac.v1.QueryListToolEntriesRequest
	(*QueryListToolEntriesResponse)(nil), // 7: lumera.cac.v1.QueryListToolEntriesResponse
	(*QueryGetParamsRequest)(nil),        // 8: lumera.cac.v1.QueryGetParamsRequest
	(*QueryGetParamsResponse)(nil),       // 9: lumera.cac.v1.QueryGetParamsResponse
	(*ToolCacheStats)(nil),               // 10: lumera.cac.v1.ToolCacheStats
	(*QueryGetToolStatsRequest)(nil),     // 11: lumera.cac.v1.QueryGetToolStatsRequest
	(*QueryGetToolStatsResponse)(nil),    // 12: lumera.cac.v1.QueryGetToolStatsResponse
	nil,                                  // 13: lumera.cac.v1.ToolCacheStats.OriginHitsEntry
	(*CacheEntry)(nil),                   // 14: lumera.cac.v1.CacheEntry
	(*CacheStats)(nil),                   // 15: lumera.cac.v1.CacheStats
	(*CacheParams)(nil),                  // 16: lumera.cac.v1.CacheParams
}
var file_lumera_cac_v1_query_proto_depIdxs = []int32{
	14, // 0: lumera.cac.v1.QueryGetCacheEntryResponse.entry:type_name -> lumera.cac.v1.CacheEntry
	14, // 1: lumera.cac.v1.QueryLookupByRequestResponse.entries:type_name -> lumera.cac.v1.CacheEntry
	15, // 2: lumera.cac.v1.QueryGetCacheStatsResponse.stats:type_name -> lumera.cac.v1.CacheStats
	14, // 3: lumera.cac.v1.QueryListToolEntriesResponse.entries:type_name -> lumera.cac.v1.CacheEntry
	16, // 4: lumera.cac.v1.QueryGetParamsResponse.params:type_name -> lumera.cac.v1.CacheParams
	13, // 5: lumera.cac.v1.ToolCacheStats.origin_hits:type_name -> lumera.cac.v1.ToolCacheStats.OriginHitsEntry
	10, // 6: lumera.cac.v1.QueryGetToolStatsResponse.stats:type_name -> lumera.cac.v1.ToolCacheStats
	0,  // 7: lumera.cac.v1.Query.GetCacheEntry:input_type -> lumera.cac.v1.QueryGetCacheEntryRequest
	2,  // 8: lumera.cac.v1.Query.LookupByRequest:input_type -> lumera.cac.v1.QueryLookupByRequestRequest
	4,  // 9: lumera.cac.v1.Query.GetCacheStats:input_type -> lumera.cac.v1.QueryGetCacheStatsRequest
	6,  // 10: lumera.cac.v1.Query.ListToolEntries:input_type -> lumera.cac.v1.QueryListToolEntriesRequest
	8,  // 11: lumera.cac.v1.Query.GetParams:input_type -> lumera.cac.v1.QueryGetParamsRequest
	11, // 12: lumera.cac.v1.Query.GetToolStats:input_type -> lumera.cac.v1.QueryGetToolStatsRequest
	1,  // 13: lumera.cac.v1.Query.GetCacheEntry:output_type -> lumera.cac.v1.QueryGetCacheEntryResponse
	3,  // 14: lumera.cac.v1.Query.LookupByRequest:output_type -> lumera.cac.v1.QueryLookupByRequestResponse
	5,  // 15: lumera.cac.v1.Query.GetCacheStats:output_type -> lumera.cac.v1.QueryGetCacheStatsResponse
	7,  // 16: lumera.cac.v1.Query.ListToolEntries:output_type -> lumera.cac.v1.QueryListToolEntriesResponse
	9,  // 17: lumera.cac.v1.Query.GetParams:output_type -> lumera.cac.v1.QueryGetParamsResponse
	12, // 18: lumera.cac.v1.Query.GetToolStats:output_type -> lumera.cac.v1.QueryGetToolStatsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_lumera_cac_v1_query_proto_init() }
func file_lumera_cac_v1_query_proto_init() {
	if File_lumera_cac_v1_query_proto != nil {
		return
	}
	file_lumera_cac_v1_cache_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lumera_cac_v1_query_proto_rawDesc), len(file_lumera_cac_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lumera_cac_v1_query_proto_goTypes,
		DependencyIndexes: file_lumera_cac_v1_query_proto_depIdxs,
		MessageInfos:      file_lumera_cac_v1_query_proto_msgTypes,
	}.Build()
	File_lumera_cac_v1_query_proto = out.File
	file_lumera_cac_v1_query_proto_goTypes = nil
	file_lumera_cac_v1_query_proto_depIdxs = nil
}
