//go:build cosmos
// +build cosmos

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: lumera/cac/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_GetCacheEntry_FullMethodName   = "/lumera.cac.v1.Query/GetCacheEntry"
	Query_LookupByRequest_FullMethodName = "/lumera.cac.v1.Query/LookupByRequest"
	Query_GetCacheStats_FullMethodName   = "/lumera.cac.v1.Query/GetCacheStats"
	Query_ListToolEntries_FullMethodName = "/lumera.cac.v1.Query/ListToolEntries"
	Query_GetParams_FullMethodName       = "/lumera.cac.v1.Query/GetParams"
	Query_GetToolStats_FullMethodName    = "/lumera.cac.v1.Query/GetToolStats"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC querier service for the CAC module
type QueryClient interface {
	// GetCacheEntry returns a specific cache entry by content hash
	GetCacheEntry(ctx context.Context, in *QueryGetCacheEntryRequest, opts ...grpc.CallOption) (*QueryGetCacheEntryResponse, error)
	// LookupByRequest looks up cache entries by request hash
	LookupByRequest(ctx context.Context, in *QueryLookupByRequestRequest, opts ...grpc.CallOption) (*QueryLookupByRequestResponse, error)
	// GetCacheStats returns cache performance statistics
	GetCacheStats(ctx context.Context, in *QueryGetCacheStatsRequest, opts ...grpc.CallOption) (*QueryGetCacheStatsResponse, error)
	// ListToolEntries lists all cache entries for a specific tool
	ListToolEntries(ctx context.Context, in *QueryListToolEntriesRequest, opts ...grpc.CallOption) (*QueryListToolEntriesResponse, error)
	// GetParams returns the module parameters
	GetParams(ctx context.Context, in *QueryGetParamsRequest, opts ...grpc.CallOption) (*QueryGetParamsResponse, error)
	// GetToolStats returns cache hit statistics for a specific tool.
	GetToolStats(ctx context.Context, in *QueryGetToolStatsRequest, opts ...grpc.CallOption) (*QueryGetToolStatsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetCacheEntry(ctx context.Context, in *QueryGetCacheEntryRequest, opts ...grpc.CallOption) (*QueryGetCacheEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetCacheEntryResponse)
	err := c.cc.Invoke(ctx, Query_GetCacheEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LookupByRequest(ctx context.Context, in *QueryLookupByRequestRequest, opts ...grpc.CallOption) (*QueryLookupByRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryLookupByRequestResponse)
	err := c.cc.Invoke(ctx, Query_LookupByRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetCacheStats(ctx context.Context, in *QueryGetCacheStatsRequest, opts ...grpc.CallOption) (*QueryGetCacheStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetCacheStatsResponse)
	err := c.cc.Invoke(ctx, Query_GetCacheStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListToolEntries(ctx context.Context, in *QueryListToolEntriesRequest, opts ...grpc.CallOption) (*QueryListToolEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListToolEntriesResponse)
	err := c.cc.Invoke(ctx, Query_ListToolEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetParams(ctx context.Context, in *QueryGetParamsRequest, opts ...grpc.CallOption) (*QueryGetParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetParamsResponse)
	err := c.cc.Invoke(ctx, Query_GetParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetToolStats(ctx context.Context, in *QueryGetToolStatsRequest, opts ...grpc.CallOption) (*QueryGetToolStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetToolStatsResponse)
	err := c.cc.Invoke(ctx, Query_GetToolStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC querier service for the CAC module
type QueryServer interface {
	// GetCacheEntry returns a specific cache entry by content hash
	GetCacheEntry(context.Context, *QueryGetCacheEntryRequest) (*QueryGetCacheEntryResponse, error)
	// LookupByRequest looks up cache entries by request hash
	LookupByRequest(context.Context, *QueryLookupByRequestRequest) (*QueryLookupByRequestResponse, error)
	// GetCacheStats returns cache performance statistics
	GetCacheStats(context.Context, *QueryGetCacheStatsRequest) (*QueryGetCacheStatsResponse, error)
	// ListToolEntries lists all cache entries for a specific tool
	ListToolEntries(context.Context, *QueryListToolEntriesRequest) (*QueryListToolEntriesResponse, error)
	// GetParams returns the module parameters
	GetParams(context.Context, *QueryGetParamsRequest) (*QueryGetParamsResponse, error)
	// GetToolStats returns cache hit statistics for a specific tool.
	GetToolStats(context.Context, *QueryGetToolStatsRequest) (*QueryGetToolStatsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) GetCacheEntry(context.Context, *QueryGetCacheEntryRequest) (*QueryGetCacheEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCacheEntry not implemented")
}
func (UnimplementedQueryServer) LookupByRequest(context.Context, *QueryLookupByRequestRequest) (*QueryLookupByRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupByRequest not implemented")
}
func (UnimplementedQueryServer) GetCacheStats(context.Context, *QueryGetCacheStatsRequest) (*QueryGetCacheStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCacheStats not implemented")
}
func (UnimplementedQueryServer) ListToolEntries(context.Context, *QueryListToolEntriesRequest) (*QueryListToolEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListToolEntries not implemented")
}
func (UnimplementedQueryServer) GetParams(context.Context, *QueryGetParamsRequest) (*QueryGetParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParams not implemented")
}
func (UnimplementedQueryServer) GetToolStats(context.Context, *QueryGetToolStatsRequest) (*QueryGetToolStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToolStats not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_GetCacheEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCacheEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetCacheEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetCacheEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetCacheEntry(ctx, req.(*QueryGetCacheEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LookupByRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLookupByRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LookupByRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LookupByRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LookupByRequest(ctx, req.(*QueryLookupByRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetCacheStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCacheStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetCacheStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetCacheStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetCacheStats(ctx, req.(*QueryGetCacheStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListToolEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListToolEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListToolEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListToolEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListToolEntries(ctx, req.(*QueryListToolEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetParams(ctx, req.(*QueryGetParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetToolStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetToolStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetToolStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetToolStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetToolStats(ctx, req.(*QueryGetToolStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lumera.cac.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCacheEntry",
			Handler:    _Query_GetCacheEntry_Handler,
		},
		{
			MethodName: "LookupByRequest",
			Handler:    _Query_LookupByRequest_Handler,
		},
		{
			MethodName: "GetCacheStats",
			Handler:    _Query_GetCacheStats_Handler,
		},
		{
			MethodName: "ListToolEntries",
			Handler:    _Query_ListToolEntries_Handler,
		},
		{
			MethodName: "GetParams",
			Handler:    _Query_GetParams_Handler,
		},
		{
			MethodName: "GetToolStats",
			Handler:    _Query_GetToolStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lumera/cac/v1/query.proto",
}
