//go:build cosmos
// +build cosmos

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lumera/cac/v1/tx.proto

package types

import (
	v1beta1 "cosmossdk.io/api/cosmos/base/v1beta1"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgCacheStore stores content in the content-addressed cache
type MsgCacheStore struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// publisher is the address of the tool publisher storing the content
	Publisher string `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
	// tool_id is the identifier of the tool producing this content
	ToolId string `protobuf:"bytes,2,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	// request_hash is the Blake3 hash of the original request
	RequestHash string `protobuf:"bytes,3,opt,name=request_hash,json=requestHash,proto3" json:"request_hash,omitempty"`
	// content is the cached response data (serialized JSON)
	Content []byte `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// ttl_seconds is the time-to-live in seconds (0 = use default)
	TtlSeconds uint64 `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// is_deterministic indicates if this tool produces deterministic output
	IsDeterministic bool `protobuf:"varint,6,opt,name=is_deterministic,json=isDeterministic,proto3" json:"is_deterministic,omitempty"`
	// royalty_eligible indicates if cache hits should trigger royalty payments
	RoyaltyEligible bool `protobuf:"varint,7,opt,name=royalty_eligible,json=royaltyEligible,proto3" json:"royalty_eligible,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MsgCacheStore) Reset() {
	*x = MsgCacheStore{}
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCacheStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCacheStore) ProtoMessage() {}

func (x *MsgCacheStore) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCacheStore.ProtoReflect.Descriptor instead.
func (*MsgCacheStore) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgCacheStore) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *MsgCacheStore) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *MsgCacheStore) GetRequestHash() string {
	if x != nil {
		return x.RequestHash
	}
	return ""
}

func (x *MsgCacheStore) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MsgCacheStore) GetTtlSeconds() uint64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *MsgCacheStore) GetIsDeterministic() bool {
	if x != nil {
		return x.IsDeterministic
	}
	return false
}

func (x *MsgCacheStore) GetRoyaltyEligible() bool {
	if x != nil {
		return x.RoyaltyEligible
	}
	return false
}

// MsgCacheStoreResponse returns the result of storing content
type MsgCacheStoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// content_hash is the Blake3 hash of the stored content (content-addressed
	// key)
	ContentHash string `protobuf:"bytes,1,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	// tier is the cache tier where content was stored
	Tier CacheTier `protobuf:"varint,2,opt,name=tier,proto3,enum=lumera.cac.v1.CacheTier" json:"tier,omitempty"`
	// expires_at is when this cache entry will expire
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCacheStoreResponse) Reset() {
	*x = MsgCacheStoreResponse{}
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCacheStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCacheStoreResponse) ProtoMessage() {}

func (x *MsgCacheStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCacheStoreResponse.ProtoReflect.Descriptor instead.
func (*MsgCacheStoreResponse) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgCacheStoreResponse) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *MsgCacheStoreResponse) GetTier() CacheTier {
	if x != nil {
		return x.Tier
	}
	return CacheTier_CACHE_TIER_UNSPECIFIED
}

func (x *MsgCacheStoreResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// MsgCacheInvalidate invalidates cache entries
type MsgCacheInvalidate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requester is the address requesting invalidation
	Requester string `protobuf:"bytes,1,opt,name=requester,proto3" json:"requester,omitempty"`
	// target_type specifies what to invalidate
	TargetType InvalidationTargetType `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3,enum=lumera.cac.v1.InvalidationTargetType" json:"target_type,omitempty"`
	// target_value is the specific target (tool_id, content_hash, or pattern)
	TargetValue string `protobuf:"bytes,3,opt,name=target_value,json=targetValue,proto3" json:"target_value,omitempty"`
	// reason explains why invalidation is being requested
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// cascade indicates if dependent entries should also be invalidated
	Cascade       bool `protobuf:"varint,5,opt,name=cascade,proto3" json:"cascade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCacheInvalidate) Reset() {
	*x = MsgCacheInvalidate{}
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCacheInvalidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCacheInvalidate) ProtoMessage() {}

func (x *MsgCacheInvalidate) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCacheInvalidate.ProtoReflect.Descriptor instead.
func (*MsgCacheInvalidate) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgCacheInvalidate) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

func (x *MsgCacheInvalidate) GetTargetType() InvalidationTargetType {
	if x != nil {
		return x.TargetType
	}
	return InvalidationTargetType_INVALIDATION_TARGET_TYPE_UNSPECIFIED
}

func (x *MsgCacheInvalidate) GetTargetValue() string {
	if x != nil {
		return x.TargetValue
	}
	return ""
}

func (x *MsgCacheInvalidate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MsgCacheInvalidate) GetCascade() bool {
	if x != nil {
		return x.Cascade
	}
	return false
}

// MsgCacheInvalidateResponse returns the result of invalidation
type MsgCacheInvalidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id is the unique identifier for this invalidation request
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// entries_invalidated is how many entries were invalidated
	EntriesInvalidated uint64 `protobuf:"varint,2,opt,name=entries_invalidated,json=entriesInvalidated,proto3" json:"entries_invalidated,omitempty"`
	// bytes_freed is how many bytes were freed
	BytesFreed    uint64 `protobuf:"varint,3,opt,name=bytes_freed,json=bytesFreed,proto3" json:"bytes_freed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCacheInvalidateResponse) Reset() {
	*x = MsgCacheInvalidateResponse{}
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCacheInvalidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCacheInvalidateResponse) ProtoMessage() {}

func (x *MsgCacheInvalidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCacheInvalidateResponse.ProtoReflect.Descriptor instead.
func (*MsgCacheInvalidateResponse) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MsgCacheInvalidateResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MsgCacheInvalidateResponse) GetEntriesInvalidated() uint64 {
	if x != nil {
		return x.EntriesInvalidated
	}
	return 0
}

func (x *MsgCacheInvalidateResponse) GetBytesFreed() uint64 {
	if x != nil {
		return x.BytesFreed
	}
	return 0
}

// MsgRecordCacheHit records a cache hit for royalty distribution
type MsgRecordCacheHit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// router is the router address recording the hit
	Router string `protobuf:"bytes,1,opt,name=router,proto3" json:"router,omitempty"`
	// content_hash is the hash of the cached content that was hit
	ContentHash string `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	// origin_tool_id is the tool that originally produced the content
	OriginToolId string `protobuf:"bytes,3,opt,name=origin_tool_id,json=originToolId,proto3" json:"origin_tool_id,omitempty"`
	// serving_tool_id is the tool serving from cache (may be same as origin)
	ServingToolId string `protobuf:"bytes,4,opt,name=serving_tool_id,json=servingToolId,proto3" json:"serving_tool_id,omitempty"`
	// requester_address is who requested the cached content
	RequesterAddress string `protobuf:"bytes,5,opt,name=requester_address,json=requesterAddress,proto3" json:"requester_address,omitempty"`
	// cost_saved is the estimated cost saved by using cache
	CostSaved []*v1beta1.Coin `protobuf:"bytes,6,rep,name=cost_saved,json=costSaved,proto3" json:"cost_saved,omitempty"`
	// latency_ms is the cache lookup latency in milliseconds
	LatencyMs uint64 `protobuf:"varint,7,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// tier is which cache tier served the hit
	Tier          CacheTier `protobuf:"varint,8,opt,name=tier,proto3,enum=lumera.cac.v1.CacheTier" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRecordCacheHit) Reset() {
	*x = MsgRecordCacheHit{}
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRecordCacheHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRecordCacheHit) ProtoMessage() {}

func (x *MsgRecordCacheHit) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRecordCacheHit.ProtoReflect.Descriptor instead.
func (*MsgRecordCacheHit) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgRecordCacheHit) GetRouter() string {
	if x != nil {
		return x.Router
	}
	return ""
}

func (x *MsgRecordCacheHit) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *MsgRecordCacheHit) GetOriginToolId() string {
	if x != nil {
		return x.OriginToolId
	}
	return ""
}

func (x *MsgRecordCacheHit) GetServingToolId() string {
	if x != nil {
		return x.ServingToolId
	}
	return ""
}

func (x *MsgRecordCacheHit) GetRequesterAddress() string {
	if x != nil {
		return x.RequesterAddress
	}
	return ""
}

func (x *MsgRecordCacheHit) GetCostSaved() []*v1beta1.Coin {
	if x != nil {
		return x.CostSaved
	}
	return nil
}

func (x *MsgRecordCacheHit) GetLatencyMs() uint64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *MsgRecordCacheHit) GetTier() CacheTier {
	if x != nil {
		return x.Tier
	}
	return CacheTier_CACHE_TIER_UNSPECIFIED
}

// MsgRecordCacheHitResponse returns the result of recording a cache hit
type MsgRecordCacheHitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hit_id is a unique identifier for this cache hit
	HitId string `protobuf:"bytes,1,opt,name=hit_id,json=hitId,proto3" json:"hit_id,omitempty"`
	// origin_royalty is the royalty amount for the origin tool
	OriginRoyalty []*v1beta1.Coin `protobuf:"bytes,2,rep,name=origin_royalty,json=originRoyalty,proto3" json:"origin_royalty,omitempty"`
	// serving_royalty is the royalty amount for the serving tool
	ServingRoyalty []*v1beta1.Coin `protobuf:"bytes,3,rep,name=serving_royalty,json=servingRoyalty,proto3" json:"serving_royalty,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgRecordCacheHitResponse) Reset() {
	*x = MsgRecordCacheHitResponse{}
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRecordCacheHitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRecordCacheHitResponse) ProtoMessage() {}

func (x *MsgRecordCacheHitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRecordCacheHitResponse.ProtoReflect.Descriptor instead.
func (*MsgRecordCacheHitResponse) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MsgRecordCacheHitResponse) GetHitId() string {
	if x != nil {
		return x.HitId
	}
	return ""
}

func (x *MsgRecordCacheHitResponse) GetOriginRoyalty() []*v1beta1.Coin {
	if x != nil {
		return x.OriginRoyalty
	}
	return nil
}

func (x *MsgRecordCacheHitResponse) GetServingRoyalty() []*v1beta1.Coin {
	if x != nil {
		return x.ServingRoyalty
	}
	return nil
}

// MsgTickDecay triggers CAC upkeep for expiry and decay accounting.
type MsgTickDecay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// authority is the governance / module authority allowed to trigger upkeep.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// limit bounds the number of expired entries processed in this tick.
	Limit         uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgTickDecay) Reset() {
	*x = MsgTickDecay{}
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgTickDecay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTickDecay) ProtoMessage() {}

func (x *MsgTickDecay) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTickDecay.ProtoReflect.Descriptor instead.
func (*MsgTickDecay) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgTickDecay) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgTickDecay) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// MsgTickDecayResponse reports the upkeep work performed.
type MsgTickDecayResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EntriesEvicted uint64                 `protobuf:"varint,1,opt,name=entries_evicted,json=entriesEvicted,proto3" json:"entries_evicted,omitempty"`
	TickHeight     int64                  `protobuf:"varint,2,opt,name=tick_height,json=tickHeight,proto3" json:"tick_height,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgTickDecayResponse) Reset() {
	*x = MsgTickDecayResponse{}
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgTickDecayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTickDecayResponse) ProtoMessage() {}

func (x *MsgTickDecayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTickDecayResponse.ProtoReflect.Descriptor instead.
func (*MsgTickDecayResponse) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_tx_proto_rawDescGZIP(), []int{7}
}

func (x *MsgTickDecayResponse) GetEntriesEvicted() uint64 {
	if x != nil {
		return x.EntriesEvicted
	}
	return 0
}

func (x *MsgTickDecayResponse) GetTickHeight() int64 {
	if x != nil {
		return x.TickHeight
	}
	return 0
}

// MsgPromoteTier promotes a cache entry to a higher tier based on access
// patterns
type MsgPromoteTier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// authority is the address with promotion authority (typically module
	// account)
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// content_hash is the hash of the entry to promote
	ContentHash string `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	// target_tier is the tier to promote to
	TargetTier    CacheTier `protobuf:"varint,3,opt,name=target_tier,json=targetTier,proto3,enum=lumera.cac.v1.CacheTier" json:"target_tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPromoteTier) Reset() {
	*x = MsgPromoteTier{}
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPromoteTier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPromoteTier) ProtoMessage() {}

func (x *MsgPromoteTier) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPromoteTier.ProtoReflect.Descriptor instead.
func (*MsgPromoteTier) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgPromoteTier) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgPromoteTier) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *MsgPromoteTier) GetTargetTier() CacheTier {
	if x != nil {
		return x.TargetTier
	}
	return CacheTier_CACHE_TIER_UNSPECIFIED
}

// MsgPromoteTierResponse returns the result of tier promotion
type MsgPromoteTierResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// previous_tier is the tier before promotion
	PreviousTier CacheTier `protobuf:"varint,1,opt,name=previous_tier,json=previousTier,proto3,enum=lumera.cac.v1.CacheTier" json:"previous_tier,omitempty"`
	// new_tier is the tier after promotion
	NewTier       CacheTier `protobuf:"varint,2,opt,name=new_tier,json=newTier,proto3,enum=lumera.cac.v1.CacheTier" json:"new_tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPromoteTierResponse) Reset() {
	*x = MsgPromoteTierResponse{}
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPromoteTierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPromoteTierResponse) ProtoMessage() {}

func (x *MsgPromoteTierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPromoteTierResponse.ProtoReflect.Descriptor instead.
func (*MsgPromoteTierResponse) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_tx_proto_rawDescGZIP(), []int{9}
}

func (x *MsgPromoteTierResponse) GetPreviousTier() CacheTier {
	if x != nil {
		return x.PreviousTier
	}
	return CacheTier_CACHE_TIER_UNSPECIFIED
}

func (x *MsgPromoteTierResponse) GetNewTier() CacheTier {
	if x != nil {
		return x.NewTier
	}
	return CacheTier_CACHE_TIER_UNSPECIFIED
}

// MsgUpdateParams updates the CAC module parameters
type MsgUpdateParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// authority is the governance address
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params are the new parameters
	Params        *CacheParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetParams() *CacheParams {
	if x != nil {
		return x.Params
	}
	return nil
}

// MsgUpdateParamsResponse confirms parameter update
type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_cac_v1_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_lumera_cac_v1_tx_proto_rawDescGZIP(), []int{11}
}

var File_lumera_cac_v1_tx_proto protoreflect.FileDescriptor

const file_lumera_cac_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x16lumera/cac/v1/tx.proto\x12\rlumera.cac.v1\x1a\x14gogoproto/gogo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ecosmos/base/v1beta1/coin.proto\x1a\x19cosmos_proto/cosmos.proto\x1a\x17cosmos/msg/v1/msg.proto\x1a\x19lumera/cac/v1/cache.proto\"\xa4\x02\n" +
	"\rMsgCacheStore\x126\n" +
	"\tpublisher\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\tpublisher\x12\x17\n" +
	"\atool_id\x18\x02 \x01(\tR\x06toolId\x12!\n" +
	"\frequest_hash\x18\x03 \x01(\tR\vrequestHash\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x04R\n" +
	"ttlSeconds\x12)\n" +
	"\x10is_deterministic\x18\x06 \x01(\bR\x0fisDeterministic\x12)\n" +
	"\x10royalty_eligible\x18\a \x01(\bR\x0froyaltyEligible:\x0e\x82\xe7\xb0*\tpublisher\"\xad\x01\n" +
	"\x15MsgCacheStoreResponse\x12!\n" +
	"\fcontent_hash\x18\x01 \x01(\tR\vcontentHash\x12,\n" +
	"\x04tier\x18\x02 \x01(\x0e2\x18.lumera.cac.v1.CacheTierR\x04tier\x12C\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\texpiresAt\"\xf9\x01\n" +
	"\x12MsgCacheInvalidate\x126\n" +
	"\trequester\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\trequester\x12F\n" +
	"\vtarget_type\x18\x02 \x01(\x0e2%.lumera.cac.v1.InvalidationTargetTypeR\n" +
	"targetType\x12!\n" +
	"\ftarget_value\x18\x03 \x01(\tR\vtargetValue\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x18\n" +
	"\acascade\x18\x05 \x01(\bR\acascade:\x0e\x82\xe7\xb0*\trequester\"\x8d\x01\n" +
	"\x1aMsgCacheInvalidateResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12/\n" +
	"\x13entries_invalidated\x18\x02 \x01(\x04R\x12entriesInvalidated\x12\x1f\n" +
	"\vbytes_freed\x18\x03 \x01(\x04R\n" +
	"bytesFreed\"\x97\x03\n" +
	"\x11MsgRecordCacheHit\x120\n" +
	"\x06router\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\x06router\x12!\n" +
	"\fcontent_hash\x18\x02 \x01(\tR\vcontentHash\x12$\n" +
	"\x0eorigin_tool_id\x18\x03 \x01(\tR\foriginToolId\x12&\n" +
	"\x0fserving_tool_id\x18\x04 \x01(\tR\rservingToolId\x12E\n" +
	"\x11requester_address\x18\x05 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\x10requesterAddress\x12>\n" +
	"\n" +
	"cost_saved\x18\x06 \x03(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\tcostSaved\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\a \x01(\x04R\tlatencyMs\x12,\n" +
	"\x04tier\x18\b \x01(\x0e2\x18.lumera.cac.v1.CacheTierR\x04tier:\v\x82\xe7\xb0*\x06router\"\xc4\x01\n" +
	"\x19MsgRecordCacheHitResponse\x12\x15\n" +
	"\x06hit_id\x18\x01 \x01(\tR\x05hitId\x12F\n" +
	"\x0eorigin_royalty\x18\x02 \x03(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\roriginRoyalty\x12H\n" +
	"\x0fserving_royalty\x18\x03 \x03(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x0eservingRoyalty\"l\n" +
	"\fMsgTickDecay\x126\n" +
	"\tauthority\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\tauthority\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit:\x0e\x82\xe7\xb0*\tauthority\"`\n" +
	"\x14MsgTickDecayResponse\x12'\n" +
	"\x0fentries_evicted\x18\x01 \x01(\x04R\x0eentriesEvicted\x12\x1f\n" +
	"\vtick_height\x18\x02 \x01(\x03R\n" +
	"tickHeight\"\xb6\x01\n" +
	"\x0eMsgPromoteTier\x126\n" +
	"\tauthority\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\tauthority\x12!\n" +
	"\fcontent_hash\x18\x02 \x01(\tR\vcontentHash\x129\n" +
	"\vtarget_tier\x18\x03 \x01(\x0e2\x18.lumera.cac.v1.CacheTierR\n" +
	"targetTier:\x0e\x82\xe7\xb0*\tauthority\"\x8c\x01\n" +
	"\x16MsgPromoteTierResponse\x12=\n" +
	"\rprevious_tier\x18\x01 \x01(\x0e2\x18.lumera.cac.v1.CacheTierR\fpreviousTier\x123\n" +
	"\bnew_tier\x18\x02 \x01(\x0e2\x18.lumera.cac.v1.CacheTierR\anewTier\"\x93\x01\n" +
	"\x0fMsgUpdateParams\x126\n" +
	"\tauthority\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\tauthority\x128\n" +
	"\x06params\x18\x02 \x01(\v2\x1a.lumera.cac.v1.CacheParamsB\x04\xc8\xde\x1f\x00R\x06params:\x0e\x82\xe7\xb0*\tauthority\"\x19\n" +
	"\x17MsgUpdateParamsResponse2\x99\x04\n" +
	"\x03Msg\x12P\n" +
	"\n" +
	"CacheStore\x12\x1c.lumera.cac.v1.MsgCacheStore\x1a$.lumera.cac.v1.MsgCacheStoreResponse\x12_\n" +
	"\x0fCacheInvalidate\x12!.lumera.cac.v1.MsgCacheInvalidate\x1a).lumera.cac.v1.MsgCacheInvalidateResponse\x12\\\n" +
	"\x0eRecordCacheHit\x12 .lumera.cac.v1.MsgRecordCacheHit\x1a(.lumera.cac.v1.MsgRecordCacheHitResponse\x12M\n" +
	"\tTickDecay\x12\x1b.lumera.cac.v1.MsgTickDecay\x1a#.lumera.cac.v1.MsgTickDecayResponse\x12S\n" +
	"\vPromoteTier\x12\x1d.lumera.cac.v1.MsgPromoteTier\x1a%.lumera.cac.v1.MsgPromoteTierResponse\x12V\n" +
	"\fUpdateParams\x12\x1e.lumera.cac.v1.MsgUpdateParams\x1a&.lumera.cac.v1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01B1Z/github.com/LumeraProtocol/lumera/x/cac/typesb\x06proto3"

var (
	file_lumera_cac_v1_tx_proto_rawDescOnce sync.Once
	file_lumera_cac_v1_tx_proto_rawDescData []byte
)

func file_lumera_cac_v1_tx_proto_rawDescGZIP() []byte {
	file_lumera_cac_v1_tx_proto_rawDescOnce.Do(func() {
		file_lumera_cac_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lumera_cac_v1_tx_proto_rawDesc), len(file_lumera_cac_v1_tx_proto_rawDesc)))
	})
	return file_lumera_cac_v1_tx_proto_rawDescData
}

var file_lumera_cac_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_lumera_cac_v1_tx_proto_goTypes = []any{
	(*MsgCacheStore)(nil),              // 0: lumera.cac.v1.MsgCacheStore
	(*MsgCacheStoreResponse)(nil),      // 1: lumera.cac.v1.MsgCacheStoreResponse
	(*MsgCacheInvalidate)(nil),         // 2: lumera.cac.v1.MsgCacheInvalidate
	(*MsgCacheInvalidateResponse)(nil), // 3: lumera.cac.v1.MsgCacheInvalidateResponse
	(*MsgRecordCacheHit)(nil),          // 4: lumera.cac.v1.MsgRecordCacheHit
	(*MsgRecordCacheHitResponse)(nil),  // 5: lumera.cac.v1.MsgRecordCacheHitResponse
	(*MsgTickDecay)(nil),               // 6: lumera.cac.v1.MsgTickDecay
	(*MsgTickDecayResponse)(nil),       // 7: lumera.cac.v1.MsgTickDecayResponse
	(*MsgPromoteTier)(nil),             // 8: lumera.cac.v1.MsgPromoteTier
	(*MsgPromoteTierResponse)(nil),     // 9: lumera.cac.v1.MsgPromoteTierResponse
	(*MsgUpdateParams)(nil),            // 10: lumera.cac.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil),    // 11: lumera.cac.v1.MsgUpdateParamsResponse
	(CacheTier)(0),                     // 12: lumera.cac.v1.CacheTier
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
	(InvalidationTargetType)(0),        // 14: lumera.cac.v1.InvalidationTargetType
	(*v1beta1.Coin)(nil),               // 15: cosmos.base.v1beta1.Coin
	(*CacheParams)(nil),                // 16: lumera.cac.v1.CacheParams
}
var file_lumera_cac_v1_tx_proto_depIdxs = []int32{
	12, // 0: lumera.cac.v1.MsgCacheStoreResponse.tier:type_name -> lumera.cac.v1.CacheTier
	13, // 1: lumera.cac.v1.MsgCacheStoreResponse.expires_at:type_name -> google.protobuf.Timestamp
	14, // 2: lumera.cac.v1.MsgCacheInvalidate.target_type:type_name -> lumera.cac.v1.InvalidationTargetType
	15, // 3: lumera.cac.v1.MsgRecordCacheHit.cost_saved:type_name -> cosmos.base.v1beta1.Coin
	12, // 4: lumera.cac.v1.MsgRecordCacheHit.tier:type_name -> lumera.cac.v1.CacheTier
	15, // 5: lumera.cac.v1.MsgRecordCacheHitResponse.origin_royalty:type_name -> cosmos.base.v1beta1.Coin
	15, // 6: lumera.cac.v1.MsgRecordCacheHitResponse.serving_royalty:type_name -> cosmos.base.v1beta1.Coin
	12, // 7: lumera.cac.v1.MsgPromoteTier.target_tier:type_name -> lumera.cac.v1.CacheTier
	12, // 8: lumera.cac.v1.MsgPromoteTierResponse.previous_tier:type_name -> lumera.cac.v1.CacheTier
	12, // 9: lumera.cac.v1.MsgPromoteTierResponse.new_tier:type_name -> lumera.cac.v1.CacheTier
	16, // 10: lumera.cac.v1.MsgUpdateParams.params:type_name -> lumera.cac.v1.CacheParams
	0,  // 11: lumera.cac.v1.Msg.CacheStore:input_type -> lumera.cac.v1.MsgCacheStore
	2,  // 12: lumera.cac.v1.Msg.CacheInvalidate:input_type -> lumera.cac.v1.MsgCacheInvalidate
	4,  // 13: lumera.cac.v1.Msg.RecordCacheHit:input_type -> lumera.cac.v1.MsgRecordCacheHit
	6,  // 14: lumera.cac.v1.Msg.TickDecay:input_type -> lumera.cac.v1.MsgTickDecay
	8,  // 15: lumera.cac.v1.Msg.PromoteTier:input_type -> lumera.cac.v1.MsgPromoteTier
	10, // 16: lumera.cac.v1.Msg.UpdateParams:input_type -> lumera.cac.v1.MsgUpdateParams
	1,  // 17: lumera.cac.v1.Msg.CacheStore:output_type -> lumera.cac.v1.MsgCacheStoreResponse
	3,  // 18: lumera.cac.v1.Msg.CacheInvalidate:output_type -> lumera.cac.v1.MsgCacheInvalidateResponse
	5,  // 19: lumera.cac.v1.Msg.RecordCacheHit:output_type -> lumera.cac.v1.MsgRecordCacheHitResponse
	7,  // 20: lumera.cac.v1.Msg.TickDecay:output_type -> lumera.cac.v1.MsgTickDecayResponse
	9,  // 21: lumera.cac.v1.Msg.PromoteTier:output_type -> lumera.cac.v1.MsgPromoteTierResponse
	11, // 22: lumera.cac.v1.Msg.UpdateParams:output_type -> lumera.cac.v1.MsgUpdateParamsResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_lumera_cac_v1_tx_proto_init() }
func file_lumera_cac_v1_tx_proto_init() {
	if File_lumera_cac_v1_tx_proto != nil {
		return
	}
	file_lumera_cac_v1_cache_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lumera_cac_v1_tx_proto_rawDesc), len(file_lumera_cac_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lumera_cac_v1_tx_proto_goTypes,
		DependencyIndexes: file_lumera_cac_v1_tx_proto_depIdxs,
		MessageInfos:      file_lumera_cac_v1_tx_proto_msgTypes,
	}.Build()
	File_lumera_cac_v1_tx_proto = out.File
	file_lumera_cac_v1_tx_proto_goTypes = nil
	file_lumera_cac_v1_tx_proto_depIdxs = nil
}
