
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: lumera/cac/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_CacheStore_FullMethodName      = "/lumera.cac.v1.Msg/CacheStore"
	Msg_CacheInvalidate_FullMethodName = "/lumera.cac.v1.Msg/CacheInvalidate"
	Msg_RecordCacheHit_FullMethodName  = "/lumera.cac.v1.Msg/RecordCacheHit"
	Msg_TickDecay_FullMethodName       = "/lumera.cac.v1.Msg/TickDecay"
	Msg_PromoteTier_FullMethodName     = "/lumera.cac.v1.Msg/PromoteTier"
	Msg_UpdateParams_FullMethodName    = "/lumera.cac.v1.Msg/UpdateParams"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the CAC module Msg service
type MsgClient interface {
	// CacheStore stores content in the cache
	CacheStore(ctx context.Context, in *MsgCacheStore, opts ...grpc.CallOption) (*MsgCacheStoreResponse, error)
	// CacheInvalidate invalidates cache entries
	CacheInvalidate(ctx context.Context, in *MsgCacheInvalidate, opts ...grpc.CallOption) (*MsgCacheInvalidateResponse, error)
	// RecordCacheHit records a cache hit for royalty distribution
	RecordCacheHit(ctx context.Context, in *MsgRecordCacheHit, opts ...grpc.CallOption) (*MsgRecordCacheHitResponse, error)
	// TickDecay performs upkeep for decay / expiry accounting.
	TickDecay(ctx context.Context, in *MsgTickDecay, opts ...grpc.CallOption) (*MsgTickDecayResponse, error)
	// PromoteTier promotes a cache entry to a higher tier
	PromoteTier(ctx context.Context, in *MsgPromoteTier, opts ...grpc.CallOption) (*MsgPromoteTierResponse, error)
	// UpdateParams updates module parameters (governance only)
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CacheStore(ctx context.Context, in *MsgCacheStore, opts ...grpc.CallOption) (*MsgCacheStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCacheStoreResponse)
	err := c.cc.Invoke(ctx, Msg_CacheStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CacheInvalidate(ctx context.Context, in *MsgCacheInvalidate, opts ...grpc.CallOption) (*MsgCacheInvalidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCacheInvalidateResponse)
	err := c.cc.Invoke(ctx, Msg_CacheInvalidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RecordCacheHit(ctx context.Context, in *MsgRecordCacheHit, opts ...grpc.CallOption) (*MsgRecordCacheHitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRecordCacheHitResponse)
	err := c.cc.Invoke(ctx, Msg_RecordCacheHit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TickDecay(ctx context.Context, in *MsgTickDecay, opts ...grpc.CallOption) (*MsgTickDecayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgTickDecayResponse)
	err := c.cc.Invoke(ctx, Msg_TickDecay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PromoteTier(ctx context.Context, in *MsgPromoteTier, opts ...grpc.CallOption) (*MsgPromoteTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgPromoteTierResponse)
	err := c.cc.Invoke(ctx, Msg_PromoteTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the CAC module Msg service
type MsgServer interface {
	// CacheStore stores content in the cache
	CacheStore(context.Context, *MsgCacheStore) (*MsgCacheStoreResponse, error)
	// CacheInvalidate invalidates cache entries
	CacheInvalidate(context.Context, *MsgCacheInvalidate) (*MsgCacheInvalidateResponse, error)
	// RecordCacheHit records a cache hit for royalty distribution
	RecordCacheHit(context.Context, *MsgRecordCacheHit) (*MsgRecordCacheHitResponse, error)
	// TickDecay performs upkeep for decay / expiry accounting.
	TickDecay(context.Context, *MsgTickDecay) (*MsgTickDecayResponse, error)
	// PromoteTier promotes a cache entry to a higher tier
	PromoteTier(context.Context, *MsgPromoteTier) (*MsgPromoteTierResponse, error)
	// UpdateParams updates module parameters (governance only)
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) CacheStore(context.Context, *MsgCacheStore) (*MsgCacheStoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CacheStore not implemented")
}
func (UnimplementedMsgServer) CacheInvalidate(context.Context, *MsgCacheInvalidate) (*MsgCacheInvalidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CacheInvalidate not implemented")
}
func (UnimplementedMsgServer) RecordCacheHit(context.Context, *MsgRecordCacheHit) (*MsgRecordCacheHitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordCacheHit not implemented")
}
func (UnimplementedMsgServer) TickDecay(context.Context, *MsgTickDecay) (*MsgTickDecayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TickDecay not implemented")
}
func (UnimplementedMsgServer) PromoteTier(context.Context, *MsgPromoteTier) (*MsgPromoteTierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PromoteTier not implemented")
}
func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_CacheStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCacheStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CacheStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CacheStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CacheStore(ctx, req.(*MsgCacheStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CacheInvalidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCacheInvalidate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CacheInvalidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CacheInvalidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CacheInvalidate(ctx, req.(*MsgCacheInvalidate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RecordCacheHit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRecordCacheHit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RecordCacheHit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RecordCacheHit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RecordCacheHit(ctx, req.(*MsgRecordCacheHit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TickDecay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTickDecay)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TickDecay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_TickDecay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TickDecay(ctx, req.(*MsgTickDecay))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PromoteTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPromoteTier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PromoteTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_PromoteTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PromoteTier(ctx, req.(*MsgPromoteTier))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lumera.cac.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CacheStore",
			Handler:    _Msg_CacheStore_Handler,
		},
		{
			MethodName: "CacheInvalidate",
			Handler:    _Msg_CacheInvalidate_Handler,
		},
		{
			MethodName: "RecordCacheHit",
			Handler:    _Msg_RecordCacheHit_Handler,
		},
		{
			MethodName: "TickDecay",
			Handler:    _Msg_TickDecay_Handler,
		},
		{
			MethodName: "PromoteTier",
			Handler:    _Msg_PromoteTier_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lumera/cac/v1/tx.proto",
}
