
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: lumera/registry/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_GetTool_FullMethodName                  = "/lumera.registry.v1.Query/GetTool"
	Query_ListTools_FullMethodName                = "/lumera.registry.v1.Query/ListTools"
	Query_GetBond_FullMethodName                  = "/lumera.registry.v1.Query/GetBond"
	Query_GetReceipt_FullMethodName               = "/lumera.registry.v1.Query/GetReceipt"
	Query_ListReceipts_FullMethodName             = "/lumera.registry.v1.Query/ListReceipts"
	Query_GetBundleAnchor_FullMethodName          = "/lumera.registry.v1.Query/GetBundleAnchor"
	Query_GetSettlement_FullMethodName            = "/lumera.registry.v1.Query/GetSettlement"
	Query_GetChallenge_FullMethodName             = "/lumera.registry.v1.Query/GetChallenge"
	Query_ListChallenges_FullMethodName           = "/lumera.registry.v1.Query/ListChallenges"
	Query_GetParams_FullMethodName                = "/lumera.registry.v1.Query/GetParams"
	Query_GetSLATemplate_FullMethodName           = "/lumera.registry.v1.Query/GetSLATemplate"
	Query_ListSLATemplates_FullMethodName         = "/lumera.registry.v1.Query/ListSLATemplates"
	Query_GetDisputeTerms_FullMethodName          = "/lumera.registry.v1.Query/GetDisputeTerms"
	Query_ListDisputeTerms_FullMethodName         = "/lumera.registry.v1.Query/ListDisputeTerms"
	Query_GetInsurancePool_FullMethodName         = "/lumera.registry.v1.Query/GetInsurancePool"
	Query_GetToolMetrics_FullMethodName           = "/lumera.registry.v1.Query/GetToolMetrics"
	Query_GetLane_FullMethodName                  = "/lumera.registry.v1.Query/GetLane"
	Query_ListLanes_FullMethodName                = "/lumera.registry.v1.Query/ListLanes"
	Query_GetToolCapsule_FullMethodName           = "/lumera.registry.v1.Query/GetToolCapsule"
	Query_ListToolCapsules_FullMethodName         = "/lumera.registry.v1.Query/ListToolCapsules"
	Query_GetOriginRoutingConfig_FullMethodName   = "/lumera.registry.v1.Query/GetOriginRoutingConfig"
	Query_ListOriginRoutingConfigs_FullMethodName = "/lumera.registry.v1.Query/ListOriginRoutingConfigs"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the registry module's gRPC query service
type QueryClient interface {
	// GetTool retrieves a specific tool by ID
	GetTool(ctx context.Context, in *QueryGetToolRequest, opts ...grpc.CallOption) (*QueryGetToolResponse, error)
	// ListTools lists all registered tools with pagination
	ListTools(ctx context.Context, in *QueryListToolsRequest, opts ...grpc.CallOption) (*QueryListToolsResponse, error)
	// GetBond retrieves bond information for a tool
	GetBond(ctx context.Context, in *QueryGetBondRequest, opts ...grpc.CallOption) (*QueryGetBondResponse, error)
	// GetReceipt retrieves a specific receipt by ID
	GetReceipt(ctx context.Context, in *QueryGetReceiptRequest, opts ...grpc.CallOption) (*QueryGetReceiptResponse, error)
	// ListReceipts lists receipts with filters
	ListReceipts(ctx context.Context, in *QueryListReceiptsRequest, opts ...grpc.CallOption) (*QueryListReceiptsResponse, error)
	// GetBundleAnchor retrieves an on-chain anchor record for a receipt bundle
	// merkle root.
	GetBundleAnchor(ctx context.Context, in *QueryGetBundleAnchorRequest, opts ...grpc.CallOption) (*QueryGetBundleAnchorResponse, error)
	// GetSettlement retrieves settlement information
	GetSettlement(ctx context.Context, in *QueryGetSettlementRequest, opts ...grpc.CallOption) (*QueryGetSettlementResponse, error)
	// GetChallenge retrieves challenge information
	GetChallenge(ctx context.Context, in *QueryGetChallengeRequest, opts ...grpc.CallOption) (*QueryGetChallengeResponse, error)
	// ListChallenges lists active challenges
	ListChallenges(ctx context.Context, in *QueryListChallengesRequest, opts ...grpc.CallOption) (*QueryListChallengesResponse, error)
	// GetParams retrieves module parameters
	GetParams(ctx context.Context, in *QueryGetParamsRequest, opts ...grpc.CallOption) (*QueryGetParamsResponse, error)
	// GetSLATemplate retrieves a stored SLA template.
	GetSLATemplate(ctx context.Context, in *QueryGetSLATemplateRequest, opts ...grpc.CallOption) (*QueryGetSLATemplateResponse, error)
	// ListSLATemplates lists all SLA templates with pagination.
	ListSLATemplates(ctx context.Context, in *QueryListSLATemplatesRequest, opts ...grpc.CallOption) (*QueryListSLATemplatesResponse, error)
	// GetDisputeTerms retrieves a stored dispute terms document.
	GetDisputeTerms(ctx context.Context, in *QueryGetDisputeTermsRequest, opts ...grpc.CallOption) (*QueryGetDisputeTermsResponse, error)
	// ListDisputeTerms lists dispute terms documents with pagination.
	ListDisputeTerms(ctx context.Context, in *QueryListDisputeTermsRequest, opts ...grpc.CallOption) (*QueryListDisputeTermsResponse, error)
	// GetInsurancePool retrieves insurance pool information
	GetInsurancePool(ctx context.Context, in *QueryGetInsurancePoolRequest, opts ...grpc.CallOption) (*QueryGetInsurancePoolResponse, error)
	// GetToolMetrics retrieves metrics for a tool
	GetToolMetrics(ctx context.Context, in *QueryGetToolMetricsRequest, opts ...grpc.CallOption) (*QueryGetToolMetricsResponse, error)
	// GetLane retrieves a lane registry entry by ID.
	GetLane(ctx context.Context, in *QueryGetLaneRequest, opts ...grpc.CallOption) (*QueryGetLaneResponse, error)
	// ListLanes lists lane registry entries with optional filters.
	ListLanes(ctx context.Context, in *QueryListLanesRequest, opts ...grpc.CallOption) (*QueryListLanesResponse, error)
	// GetToolCapsule retrieves the capsule manifest for a tool.
	GetToolCapsule(ctx context.Context, in *QueryGetToolCapsuleRequest, opts ...grpc.CallOption) (*QueryGetToolCapsuleResponse, error)
	// ListToolCapsules lists all capsule manifests with pagination.
	ListToolCapsules(ctx context.Context, in *QueryListToolCapsulesRequest, opts ...grpc.CallOption) (*QueryListToolCapsulesResponse, error)
	// GetOriginRoutingConfig retrieves an origin routing config by origin_id.
	GetOriginRoutingConfig(ctx context.Context, in *QueryGetOriginRoutingConfigRequest, opts ...grpc.CallOption) (*QueryGetOriginRoutingConfigResponse, error)
	// ListOriginRoutingConfigs lists all origin routing configs with pagination.
	ListOriginRoutingConfigs(ctx context.Context, in *QueryListOriginRoutingConfigsRequest, opts ...grpc.CallOption) (*QueryListOriginRoutingConfigsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetTool(ctx context.Context, in *QueryGetToolRequest, opts ...grpc.CallOption) (*QueryGetToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetToolResponse)
	err := c.cc.Invoke(ctx, Query_GetTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListTools(ctx context.Context, in *QueryListToolsRequest, opts ...grpc.CallOption) (*QueryListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListToolsResponse)
	err := c.cc.Invoke(ctx, Query_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetBond(ctx context.Context, in *QueryGetBondRequest, opts ...grpc.CallOption) (*QueryGetBondResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetBondResponse)
	err := c.cc.Invoke(ctx, Query_GetBond_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetReceipt(ctx context.Context, in *QueryGetReceiptRequest, opts ...grpc.CallOption) (*QueryGetReceiptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetReceiptResponse)
	err := c.cc.Invoke(ctx, Query_GetReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListReceipts(ctx context.Context, in *QueryListReceiptsRequest, opts ...grpc.CallOption) (*QueryListReceiptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListReceiptsResponse)
	err := c.cc.Invoke(ctx, Query_ListReceipts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetBundleAnchor(ctx context.Context, in *QueryGetBundleAnchorRequest, opts ...grpc.CallOption) (*QueryGetBundleAnchorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetBundleAnchorResponse)
	err := c.cc.Invoke(ctx, Query_GetBundleAnchor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetSettlement(ctx context.Context, in *QueryGetSettlementRequest, opts ...grpc.CallOption) (*QueryGetSettlementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetSettlementResponse)
	err := c.cc.Invoke(ctx, Query_GetSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetChallenge(ctx context.Context, in *QueryGetChallengeRequest, opts ...grpc.CallOption) (*QueryGetChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetChallengeResponse)
	err := c.cc.Invoke(ctx, Query_GetChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListChallenges(ctx context.Context, in *QueryListChallengesRequest, opts ...grpc.CallOption) (*QueryListChallengesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListChallengesResponse)
	err := c.cc.Invoke(ctx, Query_ListChallenges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetParams(ctx context.Context, in *QueryGetParamsRequest, opts ...grpc.CallOption) (*QueryGetParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetParamsResponse)
	err := c.cc.Invoke(ctx, Query_GetParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetSLATemplate(ctx context.Context, in *QueryGetSLATemplateRequest, opts ...grpc.CallOption) (*QueryGetSLATemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetSLATemplateResponse)
	err := c.cc.Invoke(ctx, Query_GetSLATemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListSLATemplates(ctx context.Context, in *QueryListSLATemplatesRequest, opts ...grpc.CallOption) (*QueryListSLATemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListSLATemplatesResponse)
	err := c.cc.Invoke(ctx, Query_ListSLATemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetDisputeTerms(ctx context.Context, in *QueryGetDisputeTermsRequest, opts ...grpc.CallOption) (*QueryGetDisputeTermsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetDisputeTermsResponse)
	err := c.cc.Invoke(ctx, Query_GetDisputeTerms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListDisputeTerms(ctx context.Context, in *QueryListDisputeTermsRequest, opts ...grpc.CallOption) (*QueryListDisputeTermsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListDisputeTermsResponse)
	err := c.cc.Invoke(ctx, Query_ListDisputeTerms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetInsurancePool(ctx context.Context, in *QueryGetInsurancePoolRequest, opts ...grpc.CallOption) (*QueryGetInsurancePoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetInsurancePoolResponse)
	err := c.cc.Invoke(ctx, Query_GetInsurancePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetToolMetrics(ctx context.Context, in *QueryGetToolMetricsRequest, opts ...grpc.CallOption) (*QueryGetToolMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetToolMetricsResponse)
	err := c.cc.Invoke(ctx, Query_GetToolMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetLane(ctx context.Context, in *QueryGetLaneRequest, opts ...grpc.CallOption) (*QueryGetLaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetLaneResponse)
	err := c.cc.Invoke(ctx, Query_GetLane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListLanes(ctx context.Context, in *QueryListLanesRequest, opts ...grpc.CallOption) (*QueryListLanesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListLanesResponse)
	err := c.cc.Invoke(ctx, Query_ListLanes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetToolCapsule(ctx context.Context, in *QueryGetToolCapsuleRequest, opts ...grpc.CallOption) (*QueryGetToolCapsuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetToolCapsuleResponse)
	err := c.cc.Invoke(ctx, Query_GetToolCapsule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListToolCapsules(ctx context.Context, in *QueryListToolCapsulesRequest, opts ...grpc.CallOption) (*QueryListToolCapsulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListToolCapsulesResponse)
	err := c.cc.Invoke(ctx, Query_ListToolCapsules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetOriginRoutingConfig(ctx context.Context, in *QueryGetOriginRoutingConfigRequest, opts ...grpc.CallOption) (*QueryGetOriginRoutingConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetOriginRoutingConfigResponse)
	err := c.cc.Invoke(ctx, Query_GetOriginRoutingConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListOriginRoutingConfigs(ctx context.Context, in *QueryListOriginRoutingConfigsRequest, opts ...grpc.CallOption) (*QueryListOriginRoutingConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListOriginRoutingConfigsResponse)
	err := c.cc.Invoke(ctx, Query_ListOriginRoutingConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the registry module's gRPC query service
type QueryServer interface {
	// GetTool retrieves a specific tool by ID
	GetTool(context.Context, *QueryGetToolRequest) (*QueryGetToolResponse, error)
	// ListTools lists all registered tools with pagination
	ListTools(context.Context, *QueryListToolsRequest) (*QueryListToolsResponse, error)
	// GetBond retrieves bond information for a tool
	GetBond(context.Context, *QueryGetBondRequest) (*QueryGetBondResponse, error)
	// GetReceipt retrieves a specific receipt by ID
	GetReceipt(context.Context, *QueryGetReceiptRequest) (*QueryGetReceiptResponse, error)
	// ListReceipts lists receipts with filters
	ListReceipts(context.Context, *QueryListReceiptsRequest) (*QueryListReceiptsResponse, error)
	// GetBundleAnchor retrieves an on-chain anchor record for a receipt bundle
	// merkle root.
	GetBundleAnchor(context.Context, *QueryGetBundleAnchorRequest) (*QueryGetBundleAnchorResponse, error)
	// GetSettlement retrieves settlement information
	GetSettlement(context.Context, *QueryGetSettlementRequest) (*QueryGetSettlementResponse, error)
	// GetChallenge retrieves challenge information
	GetChallenge(context.Context, *QueryGetChallengeRequest) (*QueryGetChallengeResponse, error)
	// ListChallenges lists active challenges
	ListChallenges(context.Context, *QueryListChallengesRequest) (*QueryListChallengesResponse, error)
	// GetParams retrieves module parameters
	GetParams(context.Context, *QueryGetParamsRequest) (*QueryGetParamsResponse, error)
	// GetSLATemplate retrieves a stored SLA template.
	GetSLATemplate(context.Context, *QueryGetSLATemplateRequest) (*QueryGetSLATemplateResponse, error)
	// ListSLATemplates lists all SLA templates with pagination.
	ListSLATemplates(context.Context, *QueryListSLATemplatesRequest) (*QueryListSLATemplatesResponse, error)
	// GetDisputeTerms retrieves a stored dispute terms document.
	GetDisputeTerms(context.Context, *QueryGetDisputeTermsRequest) (*QueryGetDisputeTermsResponse, error)
	// ListDisputeTerms lists dispute terms documents with pagination.
	ListDisputeTerms(context.Context, *QueryListDisputeTermsRequest) (*QueryListDisputeTermsResponse, error)
	// GetInsurancePool retrieves insurance pool information
	GetInsurancePool(context.Context, *QueryGetInsurancePoolRequest) (*QueryGetInsurancePoolResponse, error)
	// GetToolMetrics retrieves metrics for a tool
	GetToolMetrics(context.Context, *QueryGetToolMetricsRequest) (*QueryGetToolMetricsResponse, error)
	// GetLane retrieves a lane registry entry by ID.
	GetLane(context.Context, *QueryGetLaneRequest) (*QueryGetLaneResponse, error)
	// ListLanes lists lane registry entries with optional filters.
	ListLanes(context.Context, *QueryListLanesRequest) (*QueryListLanesResponse, error)
	// GetToolCapsule retrieves the capsule manifest for a tool.
	GetToolCapsule(context.Context, *QueryGetToolCapsuleRequest) (*QueryGetToolCapsuleResponse, error)
	// ListToolCapsules lists all capsule manifests with pagination.
	ListToolCapsules(context.Context, *QueryListToolCapsulesRequest) (*QueryListToolCapsulesResponse, error)
	// GetOriginRoutingConfig retrieves an origin routing config by origin_id.
	GetOriginRoutingConfig(context.Context, *QueryGetOriginRoutingConfigRequest) (*QueryGetOriginRoutingConfigResponse, error)
	// ListOriginRoutingConfigs lists all origin routing configs with pagination.
	ListOriginRoutingConfigs(context.Context, *QueryListOriginRoutingConfigsRequest) (*QueryListOriginRoutingConfigsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) GetTool(context.Context, *QueryGetToolRequest) (*QueryGetToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTool not implemented")
}
func (UnimplementedQueryServer) ListTools(context.Context, *QueryListToolsRequest) (*QueryListToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedQueryServer) GetBond(context.Context, *QueryGetBondRequest) (*QueryGetBondResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBond not implemented")
}
func (UnimplementedQueryServer) GetReceipt(context.Context, *QueryGetReceiptRequest) (*QueryGetReceiptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReceipt not implemented")
}
func (UnimplementedQueryServer) ListReceipts(context.Context, *QueryListReceiptsRequest) (*QueryListReceiptsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReceipts not implemented")
}
func (UnimplementedQueryServer) GetBundleAnchor(context.Context, *QueryGetBundleAnchorRequest) (*QueryGetBundleAnchorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBundleAnchor not implemented")
}
func (UnimplementedQueryServer) GetSettlement(context.Context, *QueryGetSettlementRequest) (*QueryGetSettlementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettlement not implemented")
}
func (UnimplementedQueryServer) GetChallenge(context.Context, *QueryGetChallengeRequest) (*QueryGetChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChallenge not implemented")
}
func (UnimplementedQueryServer) ListChallenges(context.Context, *QueryListChallengesRequest) (*QueryListChallengesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChallenges not implemented")
}
func (UnimplementedQueryServer) GetParams(context.Context, *QueryGetParamsRequest) (*QueryGetParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParams not implemented")
}
func (UnimplementedQueryServer) GetSLATemplate(context.Context, *QueryGetSLATemplateRequest) (*QueryGetSLATemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSLATemplate not implemented")
}
func (UnimplementedQueryServer) ListSLATemplates(context.Context, *QueryListSLATemplatesRequest) (*QueryListSLATemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSLATemplates not implemented")
}
func (UnimplementedQueryServer) GetDisputeTerms(context.Context, *QueryGetDisputeTermsRequest) (*QueryGetDisputeTermsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDisputeTerms not implemented")
}
func (UnimplementedQueryServer) ListDisputeTerms(context.Context, *QueryListDisputeTermsRequest) (*QueryListDisputeTermsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDisputeTerms not implemented")
}
func (UnimplementedQueryServer) GetInsurancePool(context.Context, *QueryGetInsurancePoolRequest) (*QueryGetInsurancePoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInsurancePool not implemented")
}
func (UnimplementedQueryServer) GetToolMetrics(context.Context, *QueryGetToolMetricsRequest) (*QueryGetToolMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToolMetrics not implemented")
}
func (UnimplementedQueryServer) GetLane(context.Context, *QueryGetLaneRequest) (*QueryGetLaneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLane not implemented")
}
func (UnimplementedQueryServer) ListLanes(context.Context, *QueryListLanesRequest) (*QueryListLanesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLanes not implemented")
}
func (UnimplementedQueryServer) GetToolCapsule(context.Context, *QueryGetToolCapsuleRequest) (*QueryGetToolCapsuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToolCapsule not implemented")
}
func (UnimplementedQueryServer) ListToolCapsules(context.Context, *QueryListToolCapsulesRequest) (*QueryListToolCapsulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListToolCapsules not implemented")
}
func (UnimplementedQueryServer) GetOriginRoutingConfig(context.Context, *QueryGetOriginRoutingConfigRequest) (*QueryGetOriginRoutingConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOriginRoutingConfig not implemented")
}
func (UnimplementedQueryServer) ListOriginRoutingConfigs(context.Context, *QueryListOriginRoutingConfigsRequest) (*QueryListOriginRoutingConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOriginRoutingConfigs not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_GetTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetTool(ctx, req.(*QueryGetToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListTools(ctx, req.(*QueryListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetBond_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBondRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetBond(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetBond_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetBond(ctx, req.(*QueryGetBondRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetReceipt(ctx, req.(*QueryGetReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListReceipts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListReceiptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListReceipts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListReceipts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListReceipts(ctx, req.(*QueryListReceiptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetBundleAnchor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBundleAnchorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetBundleAnchor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetBundleAnchor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetBundleAnchor(ctx, req.(*QueryGetBundleAnchorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetSettlement(ctx, req.(*QueryGetSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetChallenge(ctx, req.(*QueryGetChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListChallenges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListChallengesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListChallenges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListChallenges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListChallenges(ctx, req.(*QueryListChallengesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetParams(ctx, req.(*QueryGetParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetSLATemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSLATemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetSLATemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetSLATemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetSLATemplate(ctx, req.(*QueryGetSLATemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListSLATemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListSLATemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListSLATemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListSLATemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListSLATemplates(ctx, req.(*QueryListSLATemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetDisputeTerms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDisputeTermsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetDisputeTerms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetDisputeTerms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetDisputeTerms(ctx, req.(*QueryGetDisputeTermsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListDisputeTerms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListDisputeTermsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListDisputeTerms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListDisputeTerms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListDisputeTerms(ctx, req.(*QueryListDisputeTermsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetInsurancePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetInsurancePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetInsurancePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetInsurancePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetInsurancePool(ctx, req.(*QueryGetInsurancePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetToolMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetToolMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetToolMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetToolMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetToolMetrics(ctx, req.(*QueryGetToolMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetLane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetLane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetLane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetLane(ctx, req.(*QueryGetLaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListLanes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListLanesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListLanes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListLanes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListLanes(ctx, req.(*QueryListLanesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetToolCapsule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetToolCapsuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetToolCapsule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetToolCapsule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetToolCapsule(ctx, req.(*QueryGetToolCapsuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListToolCapsules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListToolCapsulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListToolCapsules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListToolCapsules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListToolCapsules(ctx, req.(*QueryListToolCapsulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetOriginRoutingConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetOriginRoutingConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetOriginRoutingConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetOriginRoutingConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetOriginRoutingConfig(ctx, req.(*QueryGetOriginRoutingConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListOriginRoutingConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListOriginRoutingConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListOriginRoutingConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListOriginRoutingConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListOriginRoutingConfigs(ctx, req.(*QueryListOriginRoutingConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lumera.registry.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTool",
			Handler:    _Query_GetTool_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _Query_ListTools_Handler,
		},
		{
			MethodName: "GetBond",
			Handler:    _Query_GetBond_Handler,
		},
		{
			MethodName: "GetReceipt",
			Handler:    _Query_GetReceipt_Handler,
		},
		{
			MethodName: "ListReceipts",
			Handler:    _Query_ListReceipts_Handler,
		},
		{
			MethodName: "GetBundleAnchor",
			Handler:    _Query_GetBundleAnchor_Handler,
		},
		{
			MethodName: "GetSettlement",
			Handler:    _Query_GetSettlement_Handler,
		},
		{
			MethodName: "GetChallenge",
			Handler:    _Query_GetChallenge_Handler,
		},
		{
			MethodName: "ListChallenges",
			Handler:    _Query_ListChallenges_Handler,
		},
		{
			MethodName: "GetParams",
			Handler:    _Query_GetParams_Handler,
		},
		{
			MethodName: "GetSLATemplate",
			Handler:    _Query_GetSLATemplate_Handler,
		},
		{
			MethodName: "ListSLATemplates",
			Handler:    _Query_ListSLATemplates_Handler,
		},
		{
			MethodName: "GetDisputeTerms",
			Handler:    _Query_GetDisputeTerms_Handler,
		},
		{
			MethodName: "ListDisputeTerms",
			Handler:    _Query_ListDisputeTerms_Handler,
		},
		{
			MethodName: "GetInsurancePool",
			Handler:    _Query_GetInsurancePool_Handler,
		},
		{
			MethodName: "GetToolMetrics",
			Handler:    _Query_GetToolMetrics_Handler,
		},
		{
			MethodName: "GetLane",
			Handler:    _Query_GetLane_Handler,
		},
		{
			MethodName: "ListLanes",
			Handler:    _Query_ListLanes_Handler,
		},
		{
			MethodName: "GetToolCapsule",
			Handler:    _Query_GetToolCapsule_Handler,
		},
		{
			MethodName: "ListToolCapsules",
			Handler:    _Query_ListToolCapsules_Handler,
		},
		{
			MethodName: "GetOriginRoutingConfig",
			Handler:    _Query_GetOriginRoutingConfig_Handler,
		},
		{
			MethodName: "ListOriginRoutingConfigs",
			Handler:    _Query_ListOriginRoutingConfigs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lumera/registry/v1/query.proto",
}
