package credits

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/cosmos/cosmos-sdk/client"
	legacyruntime "github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/stretchr/testify/require"
)

func TestRegisterGRPCGatewayRoutesRegistersAllCreditsQueryHTTPPaths(t *testing.T) {
	mux := legacyruntime.NewServeMux()
	AppModuleBasic{}.RegisterGRPCGatewayRoutes(client.Context{}, mux)

	// After the gogoproto migration the credits gateway exposes standard REST
	// GET routes (generated by protoc-gen-grpc-gateway) rather than the pulsar
	// gRPC method-style POST paths used pre-migration. A registered route is
	// reached by the mux and never returns 404 (it returns 500 here because the
	// test mux has no live gRPC backend); an unregistered path returns 404.
	for _, path := range []string{
		"/lumera/credits/v1/locks/test-lock-id",
		"/lumera/credits/v1/locks",
		"/lumera/credits/v1/holds/test-hold-id",
		"/lumera/credits/v1/holds",
		"/lumera/credits/v1/params",
	} {
		t.Run(path, func(t *testing.T) {
			recorder := httptest.NewRecorder()
			request := httptest.NewRequest(http.MethodGet, path, nil)

			mux.ServeHTTP(recorder, request)

			require.NotEqual(t, http.StatusNotFound, recorder.Code)
		})
	}
}
