//go:build cosmos
// +build cosmos

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lumera/reserve/v1/reserve.proto

package types

import (
	v1beta1 "cosmossdk.io/api/cosmos/base/v1beta1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReserveCommitmentStatus is the public lifecycle state exposed by reserve
// queries. It intentionally avoids private routing metadata and raw claim IDs.
type ReserveCommitmentStatus int32

const (
	ReserveCommitmentStatus_RESERVE_COMMITMENT_STATUS_UNSPECIFIED ReserveCommitmentStatus = 0
	ReserveCommitmentStatus_RESERVE_COMMITMENT_STATUS_ACTIVE      ReserveCommitmentStatus = 1
	ReserveCommitmentStatus_RESERVE_COMMITMENT_STATUS_EXPIRED     ReserveCommitmentStatus = 2
	ReserveCommitmentStatus_RESERVE_COMMITMENT_STATUS_EXHAUSTED   ReserveCommitmentStatus = 3
	ReserveCommitmentStatus_RESERVE_COMMITMENT_STATUS_REVOKED     ReserveCommitmentStatus = 4
)

// Enum value maps for ReserveCommitmentStatus.
var (
	ReserveCommitmentStatus_name = map[int32]string{
		0: "RESERVE_COMMITMENT_STATUS_UNSPECIFIED",
		1: "RESERVE_COMMITMENT_STATUS_ACTIVE",
		2: "RESERVE_COMMITMENT_STATUS_EXPIRED",
		3: "RESERVE_COMMITMENT_STATUS_EXHAUSTED",
		4: "RESERVE_COMMITMENT_STATUS_REVOKED",
	}
	ReserveCommitmentStatus_value = map[string]int32{
		"RESERVE_COMMITMENT_STATUS_UNSPECIFIED": 0,
		"RESERVE_COMMITMENT_STATUS_ACTIVE":      1,
		"RESERVE_COMMITMENT_STATUS_EXPIRED":     2,
		"RESERVE_COMMITMENT_STATUS_EXHAUSTED":   3,
		"RESERVE_COMMITMENT_STATUS_REVOKED":     4,
	}
)

func (x ReserveCommitmentStatus) Enum() *ReserveCommitmentStatus {
	p := new(ReserveCommitmentStatus)
	*p = x
	return p
}

func (x ReserveCommitmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReserveCommitmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lumera_reserve_v1_reserve_proto_enumTypes[0].Descriptor()
}

func (ReserveCommitmentStatus) Type() protoreflect.EnumType {
	return &file_lumera_reserve_v1_reserve_proto_enumTypes[0]
}

func (x ReserveCommitmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReserveCommitmentStatus.Descriptor instead.
func (ReserveCommitmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_lumera_reserve_v1_reserve_proto_rawDescGZIP(), []int{0}
}

// ReserveTierConfig describes one governance-controlled reserve SKU.
type ReserveTierConfig struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Name                   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MinCommitmentAmount    string                 `protobuf:"bytes,2,opt,name=min_commitment_amount,json=minCommitmentAmount,proto3" json:"min_commitment_amount,omitempty"`
	DiscountBps            uint32                 `protobuf:"varint,3,opt,name=discount_bps,json=discountBps,proto3" json:"discount_bps,omitempty"`
	DefaultDurationSeconds uint64                 `protobuf:"varint,4,opt,name=default_duration_seconds,json=defaultDurationSeconds,proto3" json:"default_duration_seconds,omitempty"`
	MaxActivePerPolicy     uint32                 `protobuf:"varint,5,opt,name=max_active_per_policy,json=maxActivePerPolicy,proto3" json:"max_active_per_policy,omitempty"`
	RolloverAllowed        bool                   `protobuf:"varint,6,opt,name=rollover_allowed,json=rolloverAllowed,proto3" json:"rollover_allowed,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReserveTierConfig) Reset() {
	*x = ReserveTierConfig{}
	mi := &file_lumera_reserve_v1_reserve_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveTierConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveTierConfig) ProtoMessage() {}

func (x *ReserveTierConfig) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_reserve_v1_reserve_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveTierConfig.ProtoReflect.Descriptor instead.
func (*ReserveTierConfig) Descriptor() ([]byte, []int) {
	return file_lumera_reserve_v1_reserve_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveTierConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReserveTierConfig) GetMinCommitmentAmount() string {
	if x != nil {
		return x.MinCommitmentAmount
	}
	return ""
}

func (x *ReserveTierConfig) GetDiscountBps() uint32 {
	if x != nil {
		return x.DiscountBps
	}
	return 0
}

func (x *ReserveTierConfig) GetDefaultDurationSeconds() uint64 {
	if x != nil {
		return x.DefaultDurationSeconds
	}
	return 0
}

func (x *ReserveTierConfig) GetMaxActivePerPolicy() uint32 {
	if x != nil {
		return x.MaxActivePerPolicy
	}
	return 0
}

func (x *ReserveTierConfig) GetRolloverAllowed() bool {
	if x != nil {
		return x.RolloverAllowed
	}
	return false
}

// ReserveParams is the public wire shape for reserve module parameters.
type ReserveParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreditDenom   string                 `protobuf:"bytes,1,opt,name=credit_denom,json=creditDenom,proto3" json:"credit_denom,omitempty"`
	Tiers         []*ReserveTierConfig   `protobuf:"bytes,2,rep,name=tiers,proto3" json:"tiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveParams) Reset() {
	*x = ReserveParams{}
	mi := &file_lumera_reserve_v1_reserve_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveParams) ProtoMessage() {}

func (x *ReserveParams) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_reserve_v1_reserve_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveParams.ProtoReflect.Descriptor instead.
func (*ReserveParams) Descriptor() ([]byte, []int) {
	return file_lumera_reserve_v1_reserve_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveParams) GetCreditDenom() string {
	if x != nil {
		return x.CreditDenom
	}
	return ""
}

func (x *ReserveParams) GetTiers() []*ReserveTierConfig {
	if x != nil {
		return x.Tiers
	}
	return nil
}

// ReserveCommitmentSummary is a redacted commitment view for enterprise and
// operator queries. It excludes private routing state, claim internals, and
// non-public allocation metadata.
type ReserveCommitmentSummary struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	CommitmentId    string                  `protobuf:"bytes,1,opt,name=commitment_id,json=commitmentId,proto3" json:"commitment_id,omitempty"`
	Owner           string                  `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	PolicyId        string                  `protobuf:"bytes,3,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	ToolId          string                  `protobuf:"bytes,4,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	Tier            string                  `protobuf:"bytes,5,opt,name=tier,proto3" json:"tier,omitempty"`
	TotalAmount     *v1beta1.Coin           `protobuf:"bytes,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	RemainingAmount *v1beta1.Coin           `protobuf:"bytes,7,opt,name=remaining_amount,json=remainingAmount,proto3" json:"remaining_amount,omitempty"`
	DiscountBps     uint32                  `protobuf:"varint,8,opt,name=discount_bps,json=discountBps,proto3" json:"discount_bps,omitempty"`
	StartsAt        *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	ExpiresAt       *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RolloverAllowed bool                    `protobuf:"varint,11,opt,name=rollover_allowed,json=rolloverAllowed,proto3" json:"rollover_allowed,omitempty"`
	Status          ReserveCommitmentStatus `protobuf:"varint,12,opt,name=status,proto3,enum=lumera.reserve.v1.ReserveCommitmentStatus" json:"status,omitempty"`
	RemainingBps    uint32                  `protobuf:"varint,13,opt,name=remaining_bps,json=remainingBps,proto3" json:"remaining_bps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReserveCommitmentSummary) Reset() {
	*x = ReserveCommitmentSummary{}
	mi := &file_lumera_reserve_v1_reserve_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveCommitmentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveCommitmentSummary) ProtoMessage() {}

func (x *ReserveCommitmentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_lumera_reserve_v1_reserve_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveCommitmentSummary.ProtoReflect.Descriptor instead.
func (*ReserveCommitmentSummary) Descriptor() ([]byte, []int) {
	return file_lumera_reserve_v1_reserve_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveCommitmentSummary) GetCommitmentId() string {
	if x != nil {
		return x.CommitmentId
	}
	return ""
}

func (x *ReserveCommitmentSummary) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ReserveCommitmentSummary) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ReserveCommitmentSummary) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ReserveCommitmentSummary) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *ReserveCommitmentSummary) GetTotalAmount() *v1beta1.Coin {
	if x != nil {
		return x.TotalAmount
	}
	return nil
}

func (x *ReserveCommitmentSummary) GetRemainingAmount() *v1beta1.Coin {
	if x != nil {
		return x.RemainingAmount
	}
	return nil
}

func (x *ReserveCommitmentSummary) GetDiscountBps() uint32 {
	if x != nil {
		return x.DiscountBps
	}
	return 0
}

func (x *ReserveCommitmentSummary) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *ReserveCommitmentSummary) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ReserveCommitmentSummary) GetRolloverAllowed() bool {
	if x != nil {
		return x.RolloverAllowed
	}
	return false
}

func (x *ReserveCommitmentSummary) GetStatus() ReserveCommitmentStatus {
	if x != nil {
		return x.Status
	}
	return ReserveCommitmentStatus_RESERVE_COMMITMENT_STATUS_UNSPECIFIED
}

func (x *ReserveCommitmentSummary) GetRemainingBps() uint32 {
	if x != nil {
		return x.RemainingBps
	}
	return 0
}

var File_lumera_reserve_v1_reserve_proto protoreflect.FileDescriptor

const file_lumera_reserve_v1_reserve_proto_rawDesc = "" +
	"\n" +
	"\x1flumera/reserve/v1/reserve.proto\x12\x11lumera.reserve.v1\x1a\x1ecosmos/base/v1beta1/coin.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x02\n" +
	"\x11ReserveTierConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x15min_commitment_amount\x18\x02 \x01(\tR\x13minCommitmentAmount\x12!\n" +
	"\fdiscount_bps\x18\x03 \x01(\rR\vdiscountBps\x128\n" +
	"\x18default_duration_seconds\x18\x04 \x01(\x04R\x16defaultDurationSeconds\x121\n" +
	"\x15max_active_per_policy\x18\x05 \x01(\rR\x12maxActivePerPolicy\x12)\n" +
	"\x10rollover_allowed\x18\x06 \x01(\bR\x0frolloverAllowed\"n\n" +
	"\rReserveParams\x12!\n" +
	"\fcredit_denom\x18\x01 \x01(\tR\vcreditDenom\x12:\n" +
	"\x05tiers\x18\x02 \x03(\v2$.lumera.reserve.v1.ReserveTierConfigR\x05tiers\"\xce\x04\n" +
	"\x18ReserveCommitmentSummary\x12#\n" +
	"\rcommitment_id\x18\x01 \x01(\tR\fcommitmentId\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x1b\n" +
	"\tpolicy_id\x18\x03 \x01(\tR\bpolicyId\x12\x17\n" +
	"\atool_id\x18\x04 \x01(\tR\x06toolId\x12\x12\n" +
	"\x04tier\x18\x05 \x01(\tR\x04tier\x12<\n" +
	"\ftotal_amount\x18\x06 \x01(\v2\x19.cosmos.base.v1beta1.CoinR\vtotalAmount\x12D\n" +
	"\x10remaining_amount\x18\a \x01(\v2\x19.cosmos.base.v1beta1.CoinR\x0fremainingAmount\x12!\n" +
	"\fdiscount_bps\x18\b \x01(\rR\vdiscountBps\x127\n" +
	"\tstarts_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12)\n" +
	"\x10rollover_allowed\x18\v \x01(\bR\x0frolloverAllowed\x12B\n" +
	"\x06status\x18\f \x01(\x0e2*.lumera.reserve.v1.ReserveCommitmentStatusR\x06status\x12#\n" +
	"\rremaining_bps\x18\r \x01(\rR\fremainingBps*\xe1\x01\n" +
	"\x17ReserveCommitmentStatus\x12)\n" +
	"%RESERVE_COMMITMENT_STATUS_UNSPECIFIED\x10\x00\x12$\n" +
	" RESERVE_COMMITMENT_STATUS_ACTIVE\x10\x01\x12%\n" +
	"!RESERVE_COMMITMENT_STATUS_EXPIRED\x10\x02\x12'\n" +
	"#RESERVE_COMMITMENT_STATUS_EXHAUSTED\x10\x03\x12%\n" +
	"!RESERVE_COMMITMENT_STATUS_REVOKED\x10\x04B5Z3github.com/LumeraProtocol/lumera/x/reserve/typesb\x06proto3"

var (
	file_lumera_reserve_v1_reserve_proto_rawDescOnce sync.Once
	file_lumera_reserve_v1_reserve_proto_rawDescData []byte
)

func file_lumera_reserve_v1_reserve_proto_rawDescGZIP() []byte {
	file_lumera_reserve_v1_reserve_proto_rawDescOnce.Do(func() {
		file_lumera_reserve_v1_reserve_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lumera_reserve_v1_reserve_proto_rawDesc), len(file_lumera_reserve_v1_reserve_proto_rawDesc)))
	})
	return file_lumera_reserve_v1_reserve_proto_rawDescData
}

var file_lumera_reserve_v1_reserve_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lumera_reserve_v1_reserve_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lumera_reserve_v1_reserve_proto_goTypes = []any{
	(ReserveCommitmentStatus)(0),     // 0: lumera.reserve.v1.ReserveCommitmentStatus
	(*ReserveTierConfig)(nil),        // 1: lumera.reserve.v1.ReserveTierConfig
	(*ReserveParams)(nil),            // 2: lumera.reserve.v1.ReserveParams
	(*ReserveCommitmentSummary)(nil), // 3: lumera.reserve.v1.ReserveCommitmentSummary
	(*v1beta1.Coin)(nil),             // 4: cosmos.base.v1beta1.Coin
	(*timestamppb.Timestamp)(nil),    // 5: google.protobuf.Timestamp
}
var file_lumera_reserve_v1_reserve_proto_depIdxs = []int32{
	1, // 0: lumera.reserve.v1.ReserveParams.tiers:type_name -> lumera.reserve.v1.ReserveTierConfig
	4, // 1: lumera.reserve.v1.ReserveCommitmentSummary.total_amount:type_name -> cosmos.base.v1beta1.Coin
	4, // 2: lumera.reserve.v1.ReserveCommitmentSummary.remaining_amount:type_name -> cosmos.base.v1beta1.Coin
	5, // 3: lumera.reserve.v1.ReserveCommitmentSummary.starts_at:type_name -> google.protobuf.Timestamp
	5, // 4: lumera.reserve.v1.ReserveCommitmentSummary.expires_at:type_name -> google.protobuf.Timestamp
	0, // 5: lumera.reserve.v1.ReserveCommitmentSummary.status:type_name -> lumera.reserve.v1.ReserveCommitmentStatus
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_lumera_reserve_v1_reserve_proto_init() }
func file_lumera_reserve_v1_reserve_proto_init() {
	if File_lumera_reserve_v1_reserve_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lumera_reserve_v1_reserve_proto_rawDesc), len(file_lumera_reserve_v1_reserve_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lumera_reserve_v1_reserve_proto_goTypes,
		DependencyIndexes: file_lumera_reserve_v1_reserve_proto_depIdxs,
		EnumInfos:         file_lumera_reserve_v1_reserve_proto_enumTypes,
		MessageInfos:      file_lumera_reserve_v1_reserve_proto_msgTypes,
	}.Build()
	File_lumera_reserve_v1_reserve_proto = out.File
	file_lumera_reserve_v1_reserve_proto_goTypes = nil
	file_lumera_reserve_v1_reserve_proto_depIdxs = nil
}
